// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Dense>

#include <sym/pose3.h>

namespace sym {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: spline5_pose3_acceleration
 *
 * Args:
 *     dt: Scalar
 *     lambdas: Matrix53
 *     x0: Pose3
 *     x1: Pose3
 *     x2: Pose3
 *     x3: Pose3
 *     x4: Pose3
 *     x5: Pose3
 *     epsilon: Scalar
 *
 * Outputs:
 *     res: Matrix61
 */
template <typename Scalar>
Eigen::Matrix<Scalar, 6, 1> Spline5Pose3AccelerationLocal(
    const Scalar dt, const Eigen::Matrix<Scalar, 5, 3>& lambdas, const sym::Pose3<Scalar>& x0,
    const sym::Pose3<Scalar>& x1, const sym::Pose3<Scalar>& x2, const sym::Pose3<Scalar>& x3,
    const sym::Pose3<Scalar>& x4, const sym::Pose3<Scalar>& x5, const Scalar epsilon) {
  // Total ops: 993

  // Input arrays
  const Eigen::Matrix<Scalar, 7, 1>& _x0 = x0.Data();
  const Eigen::Matrix<Scalar, 7, 1>& _x1 = x1.Data();
  const Eigen::Matrix<Scalar, 7, 1>& _x2 = x2.Data();
  const Eigen::Matrix<Scalar, 7, 1>& _x3 = x3.Data();
  const Eigen::Matrix<Scalar, 7, 1>& _x4 = x4.Data();
  const Eigen::Matrix<Scalar, 7, 1>& _x5 = x5.Data();

  // Intermediate terms (337)
  const Scalar _tmp0 = std::pow(dt, Scalar(-2));
  const Scalar _tmp1 = -_x4[0] * _x5[3] - _x4[1] * _x5[2] + _x4[2] * _x5[1] + _x4[3] * _x5[0];
  const Scalar _tmp2 = -_x4[0] * _x5[0] - _x4[1] * _x5[1] - _x4[2] * _x5[2];
  const Scalar _tmp3 = _x4[3] * _x5[3];
  const Scalar _tmp4 =
      2 * std::min<Scalar>(0, (((-_tmp2 + _tmp3) > 0) - ((-_tmp2 + _tmp3) < 0))) + 1;
  const Scalar _tmp5 = 1 - epsilon;
  const Scalar _tmp6 = std::min<Scalar>(_tmp5, std::fabs(_tmp2 - _tmp3));
  const Scalar _tmp7 = 1 - std::pow(_tmp6, Scalar(2));
  const Scalar _tmp8 = std::acos(_tmp6);
  const Scalar _tmp9 = _tmp4 * _tmp8 / std::sqrt(_tmp7);
  const Scalar _tmp10 = 2 * _tmp9;
  const Scalar _tmp11 = _tmp10 * lambdas(4, 2);
  const Scalar _tmp12 = -_x4[0] * _x5[1] + _x4[1] * _x5[0] - _x4[2] * _x5[3] + _x4[3] * _x5[2];
  const Scalar _tmp13 = std::pow(_tmp1, Scalar(2));
  const Scalar _tmp14 = std::pow(_tmp4, Scalar(2)) * std::pow(_tmp8, Scalar(2)) *
                        std::pow(lambdas(4, 0), Scalar(2)) / _tmp7;
  const Scalar _tmp15 = 4 * _tmp14;
  const Scalar _tmp16 = _x4[0] * _x5[2] - _x4[1] * _x5[3] - _x4[2] * _x5[0] + _x4[3] * _x5[1];
  const Scalar _tmp17 = std::pow(_tmp16, Scalar(2));
  const Scalar _tmp18 = std::pow(_tmp12, Scalar(2));
  const Scalar _tmp19 = std::pow(epsilon, Scalar(2));
  const Scalar _tmp20 = _tmp13 * _tmp15 + _tmp15 * _tmp17 + _tmp15 * _tmp18 + _tmp19;
  const Scalar _tmp21 = std::sqrt(_tmp20);
  const Scalar _tmp22 = (Scalar(1) / Scalar(2)) * _tmp21;
  const Scalar _tmp23 = std::cos(_tmp22);
  const Scalar _tmp24 = std::sin(_tmp22);
  const Scalar _tmp25 = _tmp24 * lambdas(4, 0) / _tmp21;
  const Scalar _tmp26 = 4 * _tmp23 * _tmp25 * _tmp9;
  const Scalar _tmp27 = _tmp12 * _tmp26;
  const Scalar _tmp28 = 8 * _tmp14 * std::pow(_tmp24, Scalar(2)) / _tmp20;
  const Scalar _tmp29 = _tmp1 * _tmp28;
  const Scalar _tmp30 = _tmp16 * _tmp29;
  const Scalar _tmp31 = _tmp27 + _tmp30;
  const Scalar _tmp32 = -_x2[0] * _x3[1] + _x2[1] * _x3[0] - _x2[2] * _x3[3] + _x2[3] * _x3[2];
  const Scalar _tmp33 = -_x2[0] * _x3[0] - _x2[1] * _x3[1] - _x2[2] * _x3[2];
  const Scalar _tmp34 = _x2[3] * _x3[3];
  const Scalar _tmp35 = std::min<Scalar>(_tmp5, std::fabs(_tmp33 - _tmp34));
  const Scalar _tmp36 = 1 - std::pow(_tmp35, Scalar(2));
  const Scalar _tmp37 =
      2 * std::min<Scalar>(0, (((-_tmp33 + _tmp34) > 0) - ((-_tmp33 + _tmp34) < 0))) + 1;
  const Scalar _tmp38 = std::acos(_tmp35);
  const Scalar _tmp39 = _tmp37 * _tmp38 / std::sqrt(_tmp36);
  const Scalar _tmp40 = 2 * _tmp39;
  const Scalar _tmp41 = _tmp32 * _tmp40;
  const Scalar _tmp42 = _tmp41 * lambdas(2, 1);
  const Scalar _tmp43 = -_x2[0] * _x3[3] - _x2[1] * _x3[2] + _x2[2] * _x3[1] + _x2[3] * _x3[0];
  const Scalar _tmp44 = _x2[0] * _x3[2] - _x2[1] * _x3[3] - _x2[2] * _x3[0] + _x2[3] * _x3[1];
  const Scalar _tmp45 = std::pow(_tmp44, Scalar(2));
  const Scalar _tmp46 = std::pow(_tmp37, Scalar(2)) * std::pow(_tmp38, Scalar(2)) *
                        std::pow(lambdas(2, 0), Scalar(2)) / _tmp36;
  const Scalar _tmp47 = 4 * _tmp46;
  const Scalar _tmp48 = std::pow(_tmp43, Scalar(2));
  const Scalar _tmp49 = std::pow(_tmp32, Scalar(2));
  const Scalar _tmp50 = _tmp19 + _tmp45 * _tmp47 + _tmp47 * _tmp48 + _tmp47 * _tmp49;
  const Scalar _tmp51 = std::sqrt(_tmp50);
  const Scalar _tmp52 = (Scalar(1) / Scalar(2)) * _tmp51;
  const Scalar _tmp53 = std::cos(_tmp52);
  const Scalar _tmp54 = std::sin(_tmp52);
  const Scalar _tmp55 = _tmp54 * lambdas(2, 0) / _tmp51;
  const Scalar _tmp56 = 4 * _tmp39 * _tmp53 * _tmp55;
  const Scalar _tmp57 = _tmp43 * _tmp56;
  const Scalar _tmp58 = 8 * _tmp46 * std::pow(_tmp54, Scalar(2)) / _tmp50;
  const Scalar _tmp59 = _tmp32 * _tmp44 * _tmp58;
  const Scalar _tmp60 = -_tmp57 + _tmp59;
  const Scalar _tmp61 = _x1[0] * _x2[2] - _x1[1] * _x2[3] - _x1[2] * _x2[0] + _x1[3] * _x2[1];
  const Scalar _tmp62 = -_x1[0] * _x2[0] - _x1[1] * _x2[1] - _x1[2] * _x2[2];
  const Scalar _tmp63 = _x1[3] * _x2[3];
  const Scalar _tmp64 = std::min<Scalar>(_tmp5, std::fabs(_tmp62 - _tmp63));
  const Scalar _tmp65 = 1 - std::pow(_tmp64, Scalar(2));
  const Scalar _tmp66 =
      2 * std::min<Scalar>(0, (((-_tmp62 + _tmp63) > 0) - ((-_tmp62 + _tmp63) < 0))) + 1;
  const Scalar _tmp67 = std::acos(_tmp64);
  const Scalar _tmp68 = _tmp66 * _tmp67 / std::sqrt(_tmp65);
  const Scalar _tmp69 = 2 * _tmp68;
  const Scalar _tmp70 = _tmp69 * lambdas(1, 1);
  const Scalar _tmp71 = _tmp61 * _tmp70;
  const Scalar _tmp72 = -_x1[0] * _x2[3] - _x1[1] * _x2[2] + _x1[2] * _x2[1] + _x1[3] * _x2[0];
  const Scalar _tmp73 = std::pow(_tmp72, Scalar(2));
  const Scalar _tmp74 = std::pow(_tmp66, Scalar(2)) * std::pow(_tmp67, Scalar(2)) *
                        std::pow(lambdas(1, 0), Scalar(2)) / _tmp65;
  const Scalar _tmp75 = 4 * _tmp74;
  const Scalar _tmp76 = -_x1[0] * _x2[1] + _x1[1] * _x2[0] - _x1[2] * _x2[3] + _x1[3] * _x2[2];
  const Scalar _tmp77 = std::pow(_tmp76, Scalar(2));
  const Scalar _tmp78 = std::pow(_tmp61, Scalar(2));
  const Scalar _tmp79 = _tmp19 + _tmp73 * _tmp75 + _tmp75 * _tmp77 + _tmp75 * _tmp78;
  const Scalar _tmp80 = std::sqrt(_tmp79);
  const Scalar _tmp81 = (Scalar(1) / Scalar(2)) * _tmp80;
  const Scalar _tmp82 = std::sin(_tmp81);
  const Scalar _tmp83 = 8 * _tmp74 * std::pow(_tmp82, Scalar(2)) / _tmp79;
  const Scalar _tmp84 = _tmp72 * _tmp83;
  const Scalar _tmp85 = _tmp61 * _tmp84;
  const Scalar _tmp86 = std::cos(_tmp81);
  const Scalar _tmp87 = _tmp82 * lambdas(1, 0) / _tmp80;
  const Scalar _tmp88 = 4 * _tmp68 * _tmp86 * _tmp87;
  const Scalar _tmp89 = _tmp76 * _tmp88;
  const Scalar _tmp90 = _tmp85 - _tmp89;
  const Scalar _tmp91 = -_x0[0] * _x1[3] - _x0[1] * _x1[2] + _x0[2] * _x1[1] + _x0[3] * _x1[0];
  const Scalar _tmp92 = -_x0[0] * _x1[0] - _x0[1] * _x1[1] - _x0[2] * _x1[2];
  const Scalar _tmp93 = _x0[3] * _x1[3];
  const Scalar _tmp94 =
      2 * std::min<Scalar>(0, (((-_tmp92 + _tmp93) > 0) - ((-_tmp92 + _tmp93) < 0))) + 1;
  const Scalar _tmp95 = std::min<Scalar>(_tmp5, std::fabs(_tmp92 - _tmp93));
  const Scalar _tmp96 = std::acos(_tmp95);
  const Scalar _tmp97 = 1 - std::pow(_tmp95, Scalar(2));
  const Scalar _tmp98 = 2 * _tmp94 * _tmp96 / std::sqrt(_tmp97);
  const Scalar _tmp99 = _tmp98 * lambdas(0, 1);
  const Scalar _tmp100 = _tmp91 * _tmp99;
  const Scalar _tmp101 = _tmp61 * _tmp76 * _tmp83;
  const Scalar _tmp102 = _tmp72 * _tmp88;
  const Scalar _tmp103 = _tmp101 + _tmp102;
  const Scalar _tmp104 = -_x0[0] * _x1[1] + _x0[1] * _x1[0] - _x0[2] * _x1[3] + _x0[3] * _x1[2];
  const Scalar _tmp105 = _tmp104 * _tmp99;
  const Scalar _tmp106 = -_tmp77 * _tmp83;
  const Scalar _tmp107 = -_tmp73 * _tmp83 + 1;
  const Scalar _tmp108 = _tmp106 + _tmp107;
  const Scalar _tmp109 = _x0[0] * _x1[2] - _x0[1] * _x1[3] - _x0[2] * _x1[0] + _x0[3] * _x1[1];
  const Scalar _tmp110 = _tmp109 * _tmp99;
  const Scalar _tmp111 = _tmp100 * _tmp90 + _tmp103 * _tmp105 + _tmp108 * _tmp110;
  const Scalar _tmp112 = _tmp111 + _tmp71;
  const Scalar _tmp113 = _tmp70 * _tmp72;
  const Scalar _tmp114 = _tmp61 * _tmp88;
  const Scalar _tmp115 = _tmp76 * _tmp84;
  const Scalar _tmp116 = -_tmp114 + _tmp115;
  const Scalar _tmp117 = -_tmp78 * _tmp83;
  const Scalar _tmp118 = _tmp106 + _tmp117 + 1;
  const Scalar _tmp119 = _tmp85 + _tmp89;
  const Scalar _tmp120 = _tmp100 * _tmp118 + _tmp105 * _tmp116 + _tmp110 * _tmp119;
  const Scalar _tmp121 = _tmp113 + _tmp120;
  const Scalar _tmp122 = _tmp44 * _tmp56;
  const Scalar _tmp123 = _tmp43 * _tmp58;
  const Scalar _tmp124 = _tmp123 * _tmp32;
  const Scalar _tmp125 = _tmp122 + _tmp124;
  const Scalar _tmp126 = -_tmp45 * _tmp58;
  const Scalar _tmp127 = -_tmp48 * _tmp58;
  const Scalar _tmp128 = _tmp126 + _tmp127 + 1;
  const Scalar _tmp129 = _tmp70 * _tmp76;
  const Scalar _tmp130 = _tmp107 + _tmp117;
  const Scalar _tmp131 = _tmp114 + _tmp115;
  const Scalar _tmp132 = _tmp109 * (_tmp101 - _tmp102);
  const Scalar _tmp133 = _tmp100 * _tmp131 + _tmp105 * _tmp130 + _tmp132 * _tmp99;
  const Scalar _tmp134 = _tmp129 + _tmp133;
  const Scalar _tmp135 = _tmp112 * _tmp60 + _tmp121 * _tmp125 + _tmp128 * _tmp134;
  const Scalar _tmp136 = _tmp135 + _tmp42;
  const Scalar _tmp137 = -_x3[0] * _x4[3] - _x3[1] * _x4[2] + _x3[2] * _x4[1] + _x3[3] * _x4[0];
  const Scalar _tmp138 = -_x3[0] * _x4[1] + _x3[1] * _x4[0] - _x3[2] * _x4[3] + _x3[3] * _x4[2];
  const Scalar _tmp139 = std::pow(_tmp137, Scalar(2));
  const Scalar _tmp140 = -_x3[0] * _x4[0] - _x3[1] * _x4[1] - _x3[2] * _x4[2];
  const Scalar _tmp141 = _x3[3] * _x4[3];
  const Scalar _tmp142 = std::min<Scalar>(_tmp5, std::fabs(_tmp140 - _tmp141));
  const Scalar _tmp143 = std::acos(_tmp142);
  const Scalar _tmp144 =
      2 * std::min<Scalar>(0, (((-_tmp140 + _tmp141) > 0) - ((-_tmp140 + _tmp141) < 0))) + 1;
  const Scalar _tmp145 = 1 - std::pow(_tmp142, Scalar(2));
  const Scalar _tmp146 = std::pow(_tmp143, Scalar(2)) * std::pow(_tmp144, Scalar(2)) *
                         std::pow(lambdas(3, 0), Scalar(2)) / _tmp145;
  const Scalar _tmp147 = 4 * _tmp146;
  const Scalar _tmp148 = std::pow(_tmp138, Scalar(2));
  const Scalar _tmp149 = _x3[0] * _x4[2] - _x3[1] * _x4[3] - _x3[2] * _x4[0] + _x3[3] * _x4[1];
  const Scalar _tmp150 = std::pow(_tmp149, Scalar(2));
  const Scalar _tmp151 = _tmp139 * _tmp147 + _tmp147 * _tmp148 + _tmp147 * _tmp150 + _tmp19;
  const Scalar _tmp152 = std::sqrt(_tmp151);
  const Scalar _tmp153 = (Scalar(1) / Scalar(2)) * _tmp152;
  const Scalar _tmp154 = std::sin(_tmp153);
  const Scalar _tmp155 = 8 * _tmp146 * std::pow(_tmp154, Scalar(2)) / _tmp151;
  const Scalar _tmp156 = _tmp137 * _tmp138 * _tmp155;
  const Scalar _tmp157 = std::cos(_tmp153);
  const Scalar _tmp158 = _tmp143 * _tmp144 / std::sqrt(_tmp145);
  const Scalar _tmp159 = _tmp154 * lambdas(3, 0) / _tmp152;
  const Scalar _tmp160 = 4 * _tmp157 * _tmp158 * _tmp159;
  const Scalar _tmp161 = _tmp149 * _tmp160;
  const Scalar _tmp162 = _tmp156 - _tmp161;
  const Scalar _tmp163 = -_tmp150 * _tmp155;
  const Scalar _tmp164 = -_tmp148 * _tmp155;
  const Scalar _tmp165 = _tmp163 + _tmp164 + 1;
  const Scalar _tmp166 = _tmp40 * _tmp43;
  const Scalar _tmp167 = _tmp166 * lambdas(2, 1);
  const Scalar _tmp168 = _tmp123 * _tmp44;
  const Scalar _tmp169 = _tmp32 * _tmp56;
  const Scalar _tmp170 = _tmp168 + _tmp169;
  const Scalar _tmp171 = -_tmp49 * _tmp58 + 1;
  const Scalar _tmp172 = _tmp126 + _tmp171;
  const Scalar _tmp173 = -_tmp122 + _tmp124;
  const Scalar _tmp174 = _tmp112 * _tmp170 + _tmp121 * _tmp172 + _tmp134 * _tmp173;
  const Scalar _tmp175 = _tmp167 + _tmp174;
  const Scalar _tmp176 = _tmp149 * _tmp155;
  const Scalar _tmp177 = _tmp137 * _tmp176;
  const Scalar _tmp178 = _tmp138 * _tmp160;
  const Scalar _tmp179 = _tmp177 + _tmp178;
  const Scalar _tmp180 = _tmp40 * _tmp44;
  const Scalar _tmp181 = _tmp180 * lambdas(2, 1);
  const Scalar _tmp182 = _tmp57 + _tmp59;
  const Scalar _tmp183 = _tmp168 - _tmp169;
  const Scalar _tmp184 = _tmp127 + _tmp171;
  const Scalar _tmp185 = _tmp112 * _tmp184 + _tmp121 * _tmp183 + _tmp134 * _tmp182;
  const Scalar _tmp186 = _tmp181 + _tmp185;
  const Scalar _tmp187 = _tmp136 * _tmp162 + _tmp165 * _tmp175 + _tmp179 * _tmp186;
  const Scalar _tmp188 = 2 * _tmp158;
  const Scalar _tmp189 = _tmp138 * _tmp188;
  const Scalar _tmp190 = _tmp189 * lambdas(3, 1);
  const Scalar _tmp191 = _tmp98 * lambdas(0, 2);
  const Scalar _tmp192 = _tmp104 * _tmp191;
  const Scalar _tmp193 = _tmp69 * lambdas(1, 2);
  const Scalar _tmp194 = _tmp191 * _tmp91;
  const Scalar _tmp195 = _tmp109 * _tmp191;
  const Scalar _tmp196 = _tmp111 * _tmp129 + _tmp116 * _tmp192 + _tmp118 * _tmp194 +
                         _tmp119 * _tmp195 - _tmp133 * _tmp71 + _tmp193 * _tmp72;
  const Scalar _tmp197 = _tmp103 * _tmp192 + _tmp108 * _tmp195 + _tmp113 * _tmp133 -
                         _tmp120 * _tmp129 + _tmp193 * _tmp61 + _tmp194 * _tmp90;
  const Scalar _tmp198 = -_tmp111 * _tmp113 + _tmp120 * _tmp71 + _tmp130 * _tmp192 +
                         _tmp131 * _tmp194 + _tmp132 * _tmp191 + _tmp193 * _tmp76;
  const Scalar _tmp199 = _tmp135 * _tmp167 - _tmp174 * _tmp42 + _tmp180 * lambdas(2, 2) +
                         _tmp182 * _tmp198 + _tmp183 * _tmp196 + _tmp184 * _tmp197;
  const Scalar _tmp200 = -_tmp139 * _tmp155 + 1;
  const Scalar _tmp201 = _tmp164 + _tmp200;
  const Scalar _tmp202 = _tmp177 - _tmp178;
  const Scalar _tmp203 = -_tmp135 * _tmp181 + _tmp166 * lambdas(2, 2) + _tmp170 * _tmp197 +
                         _tmp172 * _tmp196 + _tmp173 * _tmp198 + _tmp185 * _tmp42;
  const Scalar _tmp204 = _tmp149 * _tmp188;
  const Scalar _tmp205 = _tmp125 * _tmp196 + _tmp128 * _tmp198 - _tmp167 * _tmp185 +
                         _tmp174 * _tmp181 + _tmp197 * _tmp60 + _tmp41 * lambdas(2, 2);
  const Scalar _tmp206 = _tmp138 * _tmp176;
  const Scalar _tmp207 = _tmp137 * _tmp160;
  const Scalar _tmp208 = _tmp206 + _tmp207;
  const Scalar _tmp209 = _tmp163 + _tmp200;
  const Scalar _tmp210 = _tmp156 + _tmp161;
  const Scalar _tmp211 = _tmp206 - _tmp207;
  const Scalar _tmp212 = _tmp136 * _tmp209 + _tmp175 * _tmp210 + _tmp186 * _tmp211;
  const Scalar _tmp213 = _tmp137 * _tmp188;
  const Scalar _tmp214 = _tmp213 * lambdas(3, 1);
  const Scalar _tmp215 = -_tmp187 * _tmp190 + _tmp199 * _tmp201 + _tmp202 * _tmp203 +
                         _tmp204 * lambdas(3, 2) + _tmp205 * _tmp208 + _tmp212 * _tmp214;
  const Scalar _tmp216 = _tmp136 * _tmp208 + _tmp175 * _tmp202 + _tmp186 * _tmp201;
  const Scalar _tmp217 = _tmp204 * lambdas(3, 1);
  const Scalar _tmp218 = _tmp187 * _tmp217 + _tmp189 * lambdas(3, 2) + _tmp199 * _tmp211 +
                         _tmp203 * _tmp210 + _tmp205 * _tmp209 - _tmp214 * _tmp216;
  const Scalar _tmp219 = _tmp12 * _tmp29;
  const Scalar _tmp220 = _tmp16 * _tmp26;
  const Scalar _tmp221 = _tmp219 - _tmp220;
  const Scalar _tmp222 = -_tmp17 * _tmp28;
  const Scalar _tmp223 = -_tmp18 * _tmp28;
  const Scalar _tmp224 = _tmp222 + _tmp223 + 1;
  const Scalar _tmp225 = _tmp162 * _tmp205 + _tmp165 * _tmp203 + _tmp179 * _tmp199 +
                         _tmp190 * _tmp216 - _tmp212 * _tmp217 + _tmp213 * lambdas(3, 2);
  const Scalar _tmp226 = _tmp190 + _tmp212;
  const Scalar _tmp227 = _tmp12 * _tmp16 * _tmp28;
  const Scalar _tmp228 = _tmp1 * _tmp26;
  const Scalar _tmp229 = _tmp227 + _tmp228;
  const Scalar _tmp230 = -_tmp27 + _tmp30;
  const Scalar _tmp231 = _tmp187 + _tmp214;
  const Scalar _tmp232 = _tmp216 + _tmp217;
  const Scalar _tmp233 = -_tmp13 * _tmp28 + 1;
  const Scalar _tmp234 = _tmp223 + _tmp233;
  const Scalar _tmp235 = _tmp226 * _tmp229 + _tmp230 * _tmp231 + _tmp232 * _tmp234;
  const Scalar _tmp236 = _tmp10 * lambdas(4, 1);
  const Scalar _tmp237 = _tmp12 * _tmp236;
  const Scalar _tmp238 = _tmp222 + _tmp233;
  const Scalar _tmp239 = _tmp219 + _tmp220;
  const Scalar _tmp240 = _tmp227 - _tmp228;
  const Scalar _tmp241 = _tmp226 * _tmp238 + _tmp231 * _tmp239 + _tmp232 * _tmp240;
  const Scalar _tmp242 = _tmp16 * _tmp236;
  const Scalar _tmp243 = _tmp221 * _tmp226 + _tmp224 * _tmp231 + _tmp232 * _tmp31;
  const Scalar _tmp244 = _tmp1 * _tmp236;
  const Scalar _tmp245 = -_x1[4] + _x2[4];
  const Scalar _tmp246 = -_x4[4] + _x5[4];
  const Scalar _tmp247 = -_x3[4] + _x4[4];
  const Scalar _tmp248 = -_x2[4] + _x3[4];
  const Scalar _tmp249 = -_x0[4] + _x1[4];
  const Scalar _tmp250 = _tmp245 * lambdas(1, 2) + _tmp246 * lambdas(4, 2) +
                         _tmp247 * lambdas(3, 2) + _tmp248 * lambdas(2, 2) +
                         _tmp249 * lambdas(0, 2);
  const Scalar _tmp251 = 4 * std::pow(_tmp94, Scalar(2)) * std::pow(_tmp96, Scalar(2)) *
                         std::pow(lambdas(0, 0), Scalar(2)) / _tmp97;
  const Scalar _tmp252 = std::sqrt(Scalar(std::pow(_tmp104, Scalar(2)) * _tmp251 +
                                          std::pow(_tmp109, Scalar(2)) * _tmp251 + _tmp19 +
                                          _tmp251 * std::pow(_tmp91, Scalar(2))));
  const Scalar _tmp253 = (Scalar(1) / Scalar(2)) * _tmp252;
  const Scalar _tmp254 = _tmp98 * lambdas(0, 0) * std::sin(_tmp253) / _tmp252;
  const Scalar _tmp255 = _tmp109 * _tmp254;
  const Scalar _tmp256 = std::cos(_tmp253);
  const Scalar _tmp257 = _tmp254 * _tmp91;
  const Scalar _tmp258 = _tmp104 * _tmp254;
  const Scalar _tmp259 = -_tmp255 * _x0[2] + _tmp256 * _x0[0] + _tmp257 * _x0[3] + _tmp258 * _x0[1];
  const Scalar _tmp260 = _tmp69 * _tmp87;
  const Scalar _tmp261 = _tmp259 * _tmp260;
  const Scalar _tmp262 = _tmp255 * _x0[3] + _tmp256 * _x0[1] + _tmp257 * _x0[2] - _tmp258 * _x0[0];
  const Scalar _tmp263 = _tmp260 * _tmp262;
  const Scalar _tmp264 = _tmp255 * _x0[0] + _tmp256 * _x0[2] - _tmp257 * _x0[1] + _tmp258 * _x0[3];
  const Scalar _tmp265 = _tmp260 * _tmp264;
  const Scalar _tmp266 = -_tmp255 * _x0[1] + _tmp256 * _x0[3] - _tmp257 * _x0[0] - _tmp258 * _x0[2];
  const Scalar _tmp267 = -_tmp261 * _tmp72 - _tmp263 * _tmp61 - _tmp265 * _tmp76 + _tmp266 * _tmp86;
  const Scalar _tmp268 = _tmp41 * _tmp55;
  const Scalar _tmp269 = _tmp260 * _tmp266;
  const Scalar _tmp270 = -_tmp261 * _tmp76 + _tmp262 * _tmp86 + _tmp265 * _tmp72 + _tmp269 * _tmp61;
  const Scalar _tmp271 = _tmp166 * _tmp55;
  const Scalar _tmp272 = _tmp259 * _tmp86 + _tmp263 * _tmp76 - _tmp265 * _tmp61 + _tmp269 * _tmp72;
  const Scalar _tmp273 = _tmp180 * _tmp55;
  const Scalar _tmp274 = _tmp261 * _tmp61 - _tmp263 * _tmp72 + _tmp264 * _tmp86 + _tmp269 * _tmp76;
  const Scalar _tmp275 =
      _tmp267 * _tmp268 - _tmp270 * _tmp271 + _tmp272 * _tmp273 + _tmp274 * _tmp53;
  const Scalar _tmp276 = _tmp159 * _tmp213;
  const Scalar _tmp277 =
      _tmp267 * _tmp271 + _tmp268 * _tmp270 + _tmp272 * _tmp53 - _tmp273 * _tmp274;
  const Scalar _tmp278 = _tmp159 * _tmp189;
  const Scalar _tmp279 =
      _tmp267 * _tmp53 - _tmp268 * _tmp274 - _tmp270 * _tmp273 - _tmp271 * _tmp272;
  const Scalar _tmp280 = _tmp159 * _tmp204;
  const Scalar _tmp281 =
      _tmp267 * _tmp273 - _tmp268 * _tmp272 + _tmp270 * _tmp53 + _tmp271 * _tmp274;
  const Scalar _tmp282 =
      _tmp157 * _tmp281 + _tmp275 * _tmp276 - _tmp277 * _tmp278 + _tmp279 * _tmp280;
  const Scalar _tmp283 =
      _tmp157 * _tmp275 - _tmp276 * _tmp281 + _tmp277 * _tmp280 + _tmp278 * _tmp279;
  const Scalar _tmp284 = _tmp10 * _tmp25;
  const Scalar _tmp285 = _tmp1 * _tmp284;
  const Scalar _tmp286 =
      _tmp157 * _tmp279 - _tmp275 * _tmp278 - _tmp276 * _tmp277 - _tmp280 * _tmp281;
  const Scalar _tmp287 = _tmp284 * _tmp286;
  const Scalar _tmp288 =
      _tmp157 * _tmp277 - _tmp275 * _tmp280 + _tmp276 * _tmp279 + _tmp278 * _tmp281;
  const Scalar _tmp289 = _tmp284 * _tmp288;
  const Scalar _tmp290 =
      -_tmp12 * _tmp289 + _tmp16 * _tmp287 + _tmp23 * _tmp282 + _tmp283 * _tmp285;
  const Scalar _tmp291 = -2 * std::pow(_tmp290, Scalar(2));
  const Scalar _tmp292 = _tmp12 * _tmp287 + _tmp16 * _tmp289 + _tmp23 * _tmp283 - _tmp282 * _tmp285;
  const Scalar _tmp293 = 1 - 2 * std::pow(_tmp292, Scalar(2));
  const Scalar _tmp294 = _tmp291 + _tmp293;
  const Scalar _tmp295 = -_x1[5] + _x2[5];
  const Scalar _tmp296 = -_x4[5] + _x5[5];
  const Scalar _tmp297 = -_x3[5] + _x4[5];
  const Scalar _tmp298 = -_x2[5] + _x3[5];
  const Scalar _tmp299 = -_x0[5] + _x1[5];
  const Scalar _tmp300 = _tmp295 * lambdas(1, 2) + _tmp296 * lambdas(4, 2) +
                         _tmp297 * lambdas(3, 2) + _tmp298 * lambdas(2, 2) +
                         _tmp299 * lambdas(0, 2);
  const Scalar _tmp301 = _tmp283 * _tmp284;
  const Scalar _tmp302 = _tmp282 * _tmp284;
  const Scalar _tmp303 = _tmp12 * _tmp302 - _tmp16 * _tmp301 + _tmp23 * _tmp288 + _tmp285 * _tmp286;
  const Scalar _tmp304 = 2 * _tmp290;
  const Scalar _tmp305 = _tmp303 * _tmp304;
  const Scalar _tmp306 =
      -_tmp12 * _tmp301 - _tmp16 * _tmp302 + _tmp23 * _tmp286 - _tmp285 * _tmp288;
  const Scalar _tmp307 = 2 * _tmp292;
  const Scalar _tmp308 = _tmp306 * _tmp307;
  const Scalar _tmp309 = _tmp305 + _tmp308;
  const Scalar _tmp310 = -2 * std::pow(_tmp303, Scalar(2));
  const Scalar _tmp311 = _tmp291 + _tmp310 + 1;
  const Scalar _tmp312 = -_x1[6] + _x2[6];
  const Scalar _tmp313 = -_x4[6] + _x5[6];
  const Scalar _tmp314 = -_x3[6] + _x4[6];
  const Scalar _tmp315 = -_x2[6] + _x3[6];
  const Scalar _tmp316 = -_x0[6] + _x1[6];
  const Scalar _tmp317 = _tmp312 * lambdas(1, 1) + _tmp313 * lambdas(4, 1) +
                         _tmp314 * lambdas(3, 1) + _tmp315 * lambdas(2, 1) +
                         _tmp316 * lambdas(0, 1);
  const Scalar _tmp318 = 2 * _tmp303 * _tmp306;
  const Scalar _tmp319 = _tmp290 * _tmp307;
  const Scalar _tmp320 = -_tmp318 + _tmp319;
  const Scalar _tmp321 = _tmp295 * lambdas(1, 1) + _tmp296 * lambdas(4, 1) +
                         _tmp297 * lambdas(3, 1) + _tmp298 * lambdas(2, 1) +
                         _tmp299 * lambdas(0, 1);
  const Scalar _tmp322 = _tmp303 * _tmp307;
  const Scalar _tmp323 = _tmp304 * _tmp306;
  const Scalar _tmp324 = _tmp322 + _tmp323;
  const Scalar _tmp325 = _tmp245 * lambdas(1, 1) + _tmp246 * lambdas(4, 1) +
                         _tmp247 * lambdas(3, 1) + _tmp248 * lambdas(2, 1) +
                         _tmp249 * lambdas(0, 1);
  const Scalar _tmp326 = _tmp311 * _tmp317 + _tmp320 * _tmp321 + _tmp324 * _tmp325;
  const Scalar _tmp327 = _tmp235 + _tmp242;
  const Scalar _tmp328 = _tmp293 + _tmp310;
  const Scalar _tmp329 = _tmp305 - _tmp308;
  const Scalar _tmp330 = _tmp318 + _tmp319;
  const Scalar _tmp331 = _tmp317 * _tmp330 + _tmp321 * _tmp328 + _tmp325 * _tmp329;
  const Scalar _tmp332 = _tmp237 + _tmp241;
  const Scalar _tmp333 = _tmp322 - _tmp323;
  const Scalar _tmp334 = _tmp312 * lambdas(1, 2) + _tmp313 * lambdas(4, 2) +
                         _tmp314 * lambdas(3, 2) + _tmp315 * lambdas(2, 2) +
                         _tmp316 * lambdas(0, 2);
  const Scalar _tmp335 = _tmp243 + _tmp244;
  const Scalar _tmp336 = _tmp294 * _tmp325 + _tmp309 * _tmp321 + _tmp317 * _tmp333;

  // Output terms (1)
  Eigen::Matrix<Scalar, 6, 1> _res;

  _res(0, 0) = _tmp0 * (_tmp1 * _tmp11 + _tmp215 * _tmp31 + _tmp218 * _tmp221 + _tmp224 * _tmp225 +
                        _tmp235 * _tmp237 - _tmp241 * _tmp242);
  _res(1, 0) = _tmp0 * (_tmp11 * _tmp16 + _tmp215 * _tmp234 + _tmp218 * _tmp229 +
                        _tmp225 * _tmp230 - _tmp237 * _tmp243 + _tmp241 * _tmp244);
  _res(2, 0) = _tmp0 * (_tmp11 * _tmp12 + _tmp215 * _tmp240 + _tmp218 * _tmp238 +
                        _tmp225 * _tmp239 - _tmp235 * _tmp244 + _tmp242 * _tmp243);
  _res(3, 0) = _tmp0 * (_tmp250 * _tmp294 + _tmp300 * _tmp309 - _tmp326 * _tmp327 +
                        _tmp331 * _tmp332 + _tmp333 * _tmp334);
  _res(4, 0) = _tmp0 * (_tmp250 * _tmp329 + _tmp300 * _tmp328 + _tmp326 * _tmp335 +
                        _tmp330 * _tmp334 - _tmp332 * _tmp336);
  _res(5, 0) = _tmp0 * (_tmp250 * _tmp324 + _tmp300 * _tmp320 + _tmp311 * _tmp334 +
                        _tmp327 * _tmp336 - _tmp331 * _tmp335);

  return _res;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
