// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     COST_FUNCTION.hpp.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <ceres/sized_cost_function.h>

#include <sym/linear_camera_cal.h>
#include <sym/pose3.h>

namespace hyperion::ceres {

class Pose3CameraLinearReprojectionCostFunction final
    : public ::ceres::SizedCostFunction<2, 7, 7, 4, 3> {
 public:
  /// Constructor.
  explicit Pose3CameraLinearReprojectionCostFunction(const Eigen::Matrix<double, 2, 1>& pixel,
                                                     const Eigen::Matrix<double, 2, 2>& sqrtInfo)
      : pixel_{pixel}, sqrt_info_{sqrtInfo} {}

  /// pixel accessor.
  [[nodiscard]] auto pixel() const -> const Eigen::Matrix<double, 2, 1>& {
    return pixel_;
  }

  /// pixel modifier.
  auto pixel() -> Eigen::Matrix<double, 2, 1>& {
    return pixel_;
  }

  /// sqrtInfo accessor.
  [[nodiscard]] auto sqrtInfo() const -> const Eigen::Matrix<double, 2, 2>& {
    return sqrt_info_;
  }

  /// sqrtInfo modifier.
  auto sqrtInfo() -> Eigen::Matrix<double, 2, 2>& {
    return sqrt_info_;
  }

  /// See documentation of base class.
  /// @note Returns (tangent_dim x ambient_dim) Jacobians stored in row-major order.
  auto Evaluate(double const* const* parameters, double* residuals, double** jacobians) const
      -> bool override;

 private:
  Eigen::Matrix<double, 2, 1> pixel_;
  Eigen::Matrix<double, 2, 2> sqrt_info_;
};

}  // namespace hyperion::ceres
