// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     COST_FUNCTION.hpp.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Dense>
#include <ceres/sized_cost_function.h>

namespace hyperion::ceres {

class R2BetweenCostFunction final : public ::ceres::SizedCostFunction<2, 2, 2> {
 public:
  /// Constructor.
  explicit R2BetweenCostFunction(const Eigen::Matrix<double, 2, 1>& xTy,
                                 const Eigen::Matrix<double, 2, 2>& sqrtInfo)
      : x_T_y_{xTy}, sqrt_info_{sqrtInfo} {}

  /// xTy accessor.
  [[nodiscard]] auto xTy() const -> const Eigen::Matrix<double, 2, 1>& {
    return x_T_y_;
  }

  /// xTy modifier.
  auto xTy() -> Eigen::Matrix<double, 2, 1>& {
    return x_T_y_;
  }

  /// sqrtInfo accessor.
  [[nodiscard]] auto sqrtInfo() const -> const Eigen::Matrix<double, 2, 2>& {
    return sqrt_info_;
  }

  /// sqrtInfo modifier.
  auto sqrtInfo() -> Eigen::Matrix<double, 2, 2>& {
    return sqrt_info_;
  }

  /// See documentation of base class.
  /// @note Returns (tangent_dim x ambient_dim) Jacobians stored in row-major order.
  auto Evaluate(double const* const* parameters, double* residuals, double** jacobians) const
      -> bool override;

 private:
  Eigen::Matrix<double, 2, 1> x_T_y_;
  Eigen::Matrix<double, 2, 2> sqrt_info_;
};

}  // namespace hyperion::ceres
