// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     FACTOR.hpp.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Core>

#include <sym/pose2.h>

namespace sym_ceres {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: spline3_pose2_r2_sensor_delta_factor
 *
 * Args:
 *     lambdas: Matrix31
 *     x0: Pose2
 *     x1: Pose2
 *     x2: Pose2
 *     x3: Pose2
 *     x_T_y: Matrix21
 *     y: Pose2
 *     sqrt_info: Matrix22
 *     epsilon: Scalar
 *
 * Outputs:
 *     res: Matrix21
 *     res_D_x0: (2x4) jacobian (result_dim x storage_dim) of res (2) wrt arg x0 (4) (row-major)
 *     res_D_x1: (2x4) jacobian (result_dim x storage_dim) of res (2) wrt arg x1 (4) (row-major)
 *     res_D_x2: (2x4) jacobian (result_dim x storage_dim) of res (2) wrt arg x2 (4) (row-major)
 *     res_D_x3: (2x4) jacobian (result_dim x storage_dim) of res (2) wrt arg x3 (4) (row-major)
 *     res_D_x_T_y: (2x2) jacobian (result_dim x storage_dim) of res (2) wrt arg x_T_y (2)
 * (row-major)
 */
template <typename Scalar>
Eigen::Matrix<Scalar, 2, 1> Spline3Pose2R2SensorDeltaFactorWithJacobians12345(
    const Eigen::Matrix<Scalar, 3, 1>& lambdas, const sym::Pose2<Scalar>& x0,
    const sym::Pose2<Scalar>& x1, const sym::Pose2<Scalar>& x2, const sym::Pose2<Scalar>& x3,
    const Eigen::Matrix<Scalar, 2, 1>& x_T_y, const sym::Pose2<Scalar>& y,
    const Eigen::Matrix<Scalar, 2, 2>& sqrt_info, const Scalar epsilon,
    Scalar* const res_D_x0 = nullptr, Scalar* const res_D_x1 = nullptr,
    Scalar* const res_D_x2 = nullptr, Scalar* const res_D_x3 = nullptr,
    Scalar* const res_D_x_T_y = nullptr) {
  // Total ops: 424

  // Input arrays
  const Eigen::Matrix<Scalar, 4, 1>& _x0 = x0.Data();
  const Eigen::Matrix<Scalar, 4, 1>& _x1 = x1.Data();
  const Eigen::Matrix<Scalar, 4, 1>& _x2 = x2.Data();
  const Eigen::Matrix<Scalar, 4, 1>& _x3 = x3.Data();
  const Eigen::Matrix<Scalar, 4, 1>& _y = y.Data();

  // Intermediate terms (125)
  const Scalar _tmp0 = _x2[1] * _x3[0];
  const Scalar _tmp1 = _x2[0] * _x3[1];
  const Scalar _tmp2 = -_tmp0 + _tmp1;
  const Scalar _tmp3 = _x2[0] * _x3[0];
  const Scalar _tmp4 = _x2[1] * _x3[1];
  const Scalar _tmp5 = _tmp3 + _tmp4;
  const Scalar _tmp6 = _tmp5 + epsilon * ((((_tmp5) > 0) - ((_tmp5) < 0)) + Scalar(0.5));
  const Scalar _tmp7 = lambdas(2, 0) * std::atan2(_tmp2, _tmp6);
  const Scalar _tmp8 = std::sin(_tmp7);
  const Scalar _tmp9 = _x1[0] * _x2[1];
  const Scalar _tmp10 = _x1[1] * _x2[0];
  const Scalar _tmp11 = -_tmp10 + _tmp9;
  const Scalar _tmp12 = _x1[0] * _x2[0];
  const Scalar _tmp13 = _x1[1] * _x2[1];
  const Scalar _tmp14 = _tmp12 + _tmp13;
  const Scalar _tmp15 = _tmp14 + epsilon * ((((_tmp14) > 0) - ((_tmp14) < 0)) + Scalar(0.5));
  const Scalar _tmp16 = lambdas(1, 0) * std::atan2(_tmp11, _tmp15);
  const Scalar _tmp17 = std::sin(_tmp16);
  const Scalar _tmp18 = _tmp17 * _tmp8;
  const Scalar _tmp19 = std::cos(_tmp7);
  const Scalar _tmp20 = std::cos(_tmp16);
  const Scalar _tmp21 = _tmp19 * _tmp20;
  const Scalar _tmp22 = -_tmp18 + _tmp21;
  const Scalar _tmp23 = _x0[1] * _x1[0];
  const Scalar _tmp24 = _x0[0] * _x1[1];
  const Scalar _tmp25 = -_tmp23 + _tmp24;
  const Scalar _tmp26 = _x0[1] * _x1[1];
  const Scalar _tmp27 = _x0[0] * _x1[0];
  const Scalar _tmp28 = _tmp26 + _tmp27;
  const Scalar _tmp29 = _tmp28 + epsilon * ((((_tmp28) > 0) - ((_tmp28) < 0)) + Scalar(0.5));
  const Scalar _tmp30 = lambdas(0, 0) * std::atan2(_tmp25, _tmp29);
  const Scalar _tmp31 = std::cos(_tmp30);
  const Scalar _tmp32 = _tmp22 * _tmp31;
  const Scalar _tmp33 = _tmp20 * _tmp8;
  const Scalar _tmp34 = _tmp17 * _tmp19;
  const Scalar _tmp35 = _tmp33 + _tmp34;
  const Scalar _tmp36 = std::sin(_tmp30);
  const Scalar _tmp37 = _tmp35 * _tmp36;
  const Scalar _tmp38 = _tmp32 - _tmp37;
  const Scalar _tmp39 = _tmp38 * _x0[1];
  const Scalar _tmp40 = _tmp22 * _tmp36;
  const Scalar _tmp41 = _tmp31 * _tmp35;
  const Scalar _tmp42 = _tmp40 + _tmp41;
  const Scalar _tmp43 = _tmp42 * _x0[0];
  const Scalar _tmp44 = _tmp39 + _tmp43;
  const Scalar _tmp45 = _x0[2] + lambdas(0, 0) * (-_x0[2] + _x1[2]) +
                        lambdas(1, 0) * (-_x1[2] + _x2[2]) + lambdas(2, 0) * (-_x2[2] + _x3[2]);
  const Scalar _tmp46 = _tmp38 * _x0[0] - _tmp42 * _x0[1];
  const Scalar _tmp47 = _x0[3] + lambdas(0, 0) * (-_x0[3] + _x1[3]) +
                        lambdas(1, 0) * (-_x1[3] + _x2[3]) + lambdas(2, 0) * (-_x2[3] + _x3[3]);
  const Scalar _tmp48 =
      _tmp44 * _tmp45 - _tmp44 * _y[2] - _tmp46 * _tmp47 + _tmp46 * _y[3] - x_T_y(1, 0);
  const Scalar _tmp49 =
      -_tmp44 * _tmp47 + _tmp44 * _y[3] - _tmp45 * _tmp46 + _tmp46 * _y[2] - x_T_y(0, 0);
  const Scalar _tmp50 = std::pow(_tmp25, Scalar(2));
  const Scalar _tmp51 = std::pow(_tmp29, Scalar(2));
  const Scalar _tmp52 = Scalar(1.0) / (_tmp51);
  const Scalar _tmp53 = Scalar(1.0) / (_tmp29);
  const Scalar _tmp54 = _tmp51 * lambdas(0, 0) / (_tmp50 + _tmp51);
  const Scalar _tmp55 = _tmp54 * (-_tmp50 * _tmp52 + _tmp53 * (-_tmp26 - _tmp27));
  const Scalar _tmp56 = _tmp32 * _tmp55 - _tmp37 * _tmp55;
  const Scalar _tmp57 = -_tmp40 * _tmp55 - _tmp41 * _tmp55;
  const Scalar _tmp58 = _tmp46 + _tmp56 * _x0[0] + _tmp57 * _x0[1];
  const Scalar _tmp59 = -_tmp39 - _tmp43 - _tmp56 * _x0[1] + _tmp57 * _x0[0];
  const Scalar _tmp60 = -_tmp45 * _tmp59 - _tmp47 * _tmp58 + _tmp58 * _y[3] + _tmp59 * _y[2];
  const Scalar _tmp61 = _tmp45 * _tmp58 - _tmp47 * _tmp59 - _tmp58 * _y[2] + _tmp59 * _y[3];
  const Scalar _tmp62 = _tmp60 * sqrt_info(0, 0) + _tmp61 * sqrt_info(0, 1);
  const Scalar _tmp63 = _tmp60 * sqrt_info(1, 0) + _tmp61 * sqrt_info(1, 1);
  const Scalar _tmp64 = 1 - lambdas(0, 0);
  const Scalar _tmp65 = _tmp44 * _tmp64;
  const Scalar _tmp66 = _tmp46 * _tmp64;
  const Scalar _tmp67 = _tmp44 * sqrt_info(1, 1);
  const Scalar _tmp68 = _tmp44 * sqrt_info(0, 0);
  const Scalar _tmp69 = std::pow(_tmp11, Scalar(2));
  const Scalar _tmp70 = std::pow(_tmp15, Scalar(2));
  const Scalar _tmp71 = Scalar(1.0) / (_tmp70);
  const Scalar _tmp72 = Scalar(1.0) / (_tmp15);
  const Scalar _tmp73 = _tmp70 * lambdas(1, 0) / (_tmp69 + _tmp70);
  const Scalar _tmp74 = _tmp73 * (-_tmp69 * _tmp71 + _tmp72 * (-_tmp12 - _tmp13));
  const Scalar _tmp75 = -_tmp18 * _tmp74 + _tmp21 * _tmp74;
  const Scalar _tmp76 = -_tmp33 * _tmp74 - _tmp34 * _tmp74;
  const Scalar _tmp77 = _tmp54 * (-_tmp25 * _tmp52 * (_tmp23 - _tmp24) + _tmp28 * _tmp53);
  const Scalar _tmp78 = _tmp31 * _tmp75 + _tmp32 * _tmp77 + _tmp36 * _tmp76 - _tmp37 * _tmp77;
  const Scalar _tmp79 = _tmp31 * _tmp76 - _tmp36 * _tmp75 - _tmp40 * _tmp77 - _tmp41 * _tmp77;
  const Scalar _tmp80 = _tmp78 * _x0[0] + _tmp79 * _x0[1];
  const Scalar _tmp81 = -_tmp78 * _x0[1] + _tmp79 * _x0[0];
  const Scalar _tmp82 = _tmp45 * _tmp80 - _tmp47 * _tmp81 - _tmp80 * _y[2] + _tmp81 * _y[3];
  const Scalar _tmp83 = -_tmp45 * _tmp81 - _tmp47 * _tmp80 + _tmp80 * _y[3] + _tmp81 * _y[2];
  const Scalar _tmp84 = _tmp82 * sqrt_info(0, 1) + _tmp83 * sqrt_info(0, 0);
  const Scalar _tmp85 = _tmp82 * sqrt_info(1, 1) + _tmp83 * sqrt_info(1, 0);
  const Scalar _tmp86 = lambdas(0, 0) - lambdas(1, 0);
  const Scalar _tmp87 = _tmp44 * _tmp86;
  const Scalar _tmp88 = _tmp46 * _tmp86;
  const Scalar _tmp89 = std::pow(_tmp2, Scalar(2));
  const Scalar _tmp90 = std::pow(_tmp6, Scalar(2));
  const Scalar _tmp91 = Scalar(1.0) / (_tmp90);
  const Scalar _tmp92 = Scalar(1.0) / (_tmp6);
  const Scalar _tmp93 = -_tmp89 * _tmp91 + _tmp92 * (-_tmp3 - _tmp4);
  const Scalar _tmp94 = _tmp90 * lambdas(2, 0) / (_tmp89 + _tmp90);
  const Scalar _tmp95 = _tmp93 * _tmp94;
  const Scalar _tmp96 = _tmp34 * _tmp94;
  const Scalar _tmp97 = _tmp73 * (-_tmp11 * _tmp71 * (_tmp10 - _tmp9) + _tmp14 * _tmp72);
  const Scalar _tmp98 = -_tmp33 * _tmp95 - _tmp33 * _tmp97 - _tmp34 * _tmp97 - _tmp93 * _tmp96;
  const Scalar _tmp99 = -_tmp18 * _tmp95 - _tmp18 * _tmp97 + _tmp21 * _tmp95 + _tmp21 * _tmp97;
  const Scalar _tmp100 = _tmp31 * _tmp99 + _tmp36 * _tmp98;
  const Scalar _tmp101 = _tmp31 * _tmp98 - _tmp36 * _tmp99;
  const Scalar _tmp102 = -_tmp100 * _x0[1] + _tmp101 * _x0[0];
  const Scalar _tmp103 = _tmp100 * _x0[0] + _tmp101 * _x0[1];
  const Scalar _tmp104 = -_tmp102 * _tmp47 + _tmp102 * _y[3] + _tmp103 * _tmp45 - _tmp103 * _y[2];
  const Scalar _tmp105 = -_tmp102 * _tmp45 + _tmp102 * _y[2] - _tmp103 * _tmp47 + _tmp103 * _y[3];
  const Scalar _tmp106 = _tmp104 * sqrt_info(0, 1) + _tmp105 * sqrt_info(0, 0);
  const Scalar _tmp107 = _tmp104 * sqrt_info(1, 1) + _tmp105 * sqrt_info(1, 0);
  const Scalar _tmp108 = lambdas(1, 0) - lambdas(2, 0);
  const Scalar _tmp109 = _tmp108 * _tmp44;
  const Scalar _tmp110 = _tmp108 * _tmp46;
  const Scalar _tmp111 = -_tmp2 * _tmp91 * (_tmp0 - _tmp1) + _tmp5 * _tmp92;
  const Scalar _tmp112 = _tmp111 * _tmp94;
  const Scalar _tmp113 = -_tmp112 * _tmp18 + _tmp112 * _tmp21;
  const Scalar _tmp114 = -_tmp111 * _tmp96 - _tmp112 * _tmp33;
  const Scalar _tmp115 = -_tmp113 * _tmp36 + _tmp114 * _tmp31;
  const Scalar _tmp116 = _tmp113 * _tmp31 + _tmp114 * _tmp36;
  const Scalar _tmp117 = _tmp115 * _x0[1] + _tmp116 * _x0[0];
  const Scalar _tmp118 = _tmp115 * _x0[0] - _tmp116 * _x0[1];
  const Scalar _tmp119 = _tmp117 * _tmp45 - _tmp117 * _y[2] - _tmp118 * _tmp47 + _tmp118 * _y[3];
  const Scalar _tmp120 = -_tmp117 * _tmp47 + _tmp117 * _y[3] - _tmp118 * _tmp45 + _tmp118 * _y[2];
  const Scalar _tmp121 = _tmp119 * sqrt_info(0, 1) + _tmp120 * sqrt_info(0, 0);
  const Scalar _tmp122 = _tmp119 * sqrt_info(1, 1) + _tmp120 * sqrt_info(1, 0);
  const Scalar _tmp123 = _tmp44 * lambdas(2, 0);
  const Scalar _tmp124 = _tmp46 * lambdas(2, 0);

  // Output terms (6)
  Eigen::Matrix<Scalar, 2, 1> _res;

  _res(0, 0) = _tmp48 * sqrt_info(0, 1) + _tmp49 * sqrt_info(0, 0);
  _res(1, 0) = _tmp48 * sqrt_info(1, 1) + _tmp49 * sqrt_info(1, 0);

  if (res_D_x0 != nullptr) {
    Eigen::Map<Eigen::Matrix<Scalar, 2, 4, Eigen::RowMajor>> _res_D_x0{res_D_x0};

    _res_D_x0(0, 0) = -_tmp62 * _x0[1];
    _res_D_x0(1, 0) = -_tmp63 * _x0[1];
    _res_D_x0(0, 1) = _tmp62 * _x0[0];
    _res_D_x0(1, 1) = _tmp63 * _x0[0];
    _res_D_x0(0, 2) = _tmp65 * sqrt_info(0, 1) - _tmp66 * sqrt_info(0, 0);
    _res_D_x0(1, 2) = _tmp64 * _tmp67 - _tmp66 * sqrt_info(1, 0);
    _res_D_x0(0, 3) = -_tmp64 * _tmp68 - _tmp66 * sqrt_info(0, 1);
    _res_D_x0(1, 3) = -_tmp65 * sqrt_info(1, 0) - _tmp66 * sqrt_info(1, 1);
  }

  if (res_D_x1 != nullptr) {
    Eigen::Map<Eigen::Matrix<Scalar, 2, 4, Eigen::RowMajor>> _res_D_x1{res_D_x1};

    _res_D_x1(0, 0) = -_tmp84 * _x1[1];
    _res_D_x1(1, 0) = -_tmp85 * _x1[1];
    _res_D_x1(0, 1) = _tmp84 * _x1[0];
    _res_D_x1(1, 1) = _tmp85 * _x1[0];
    _res_D_x1(0, 2) = _tmp87 * sqrt_info(0, 1) - _tmp88 * sqrt_info(0, 0);
    _res_D_x1(1, 2) = _tmp67 * _tmp86 - _tmp88 * sqrt_info(1, 0);
    _res_D_x1(0, 3) = -_tmp68 * _tmp86 - _tmp88 * sqrt_info(0, 1);
    _res_D_x1(1, 3) = -_tmp87 * sqrt_info(1, 0) - _tmp88 * sqrt_info(1, 1);
  }

  if (res_D_x2 != nullptr) {
    Eigen::Map<Eigen::Matrix<Scalar, 2, 4, Eigen::RowMajor>> _res_D_x2{res_D_x2};

    _res_D_x2(0, 0) = -_tmp106 * _x2[1];
    _res_D_x2(1, 0) = -_tmp107 * _x2[1];
    _res_D_x2(0, 1) = _tmp106 * _x2[0];
    _res_D_x2(1, 1) = _tmp107 * _x2[0];
    _res_D_x2(0, 2) = _tmp109 * sqrt_info(0, 1) - _tmp110 * sqrt_info(0, 0);
    _res_D_x2(1, 2) = _tmp108 * _tmp67 - _tmp110 * sqrt_info(1, 0);
    _res_D_x2(0, 3) = -_tmp108 * _tmp68 - _tmp110 * sqrt_info(0, 1);
    _res_D_x2(1, 3) = -_tmp109 * sqrt_info(1, 0) - _tmp110 * sqrt_info(1, 1);
  }

  if (res_D_x3 != nullptr) {
    Eigen::Map<Eigen::Matrix<Scalar, 2, 4, Eigen::RowMajor>> _res_D_x3{res_D_x3};

    _res_D_x3(0, 0) = -_tmp121 * _x3[1];
    _res_D_x3(1, 0) = -_tmp122 * _x3[1];
    _res_D_x3(0, 1) = _tmp121 * _x3[0];
    _res_D_x3(1, 1) = _tmp122 * _x3[0];
    _res_D_x3(0, 2) = _tmp123 * sqrt_info(0, 1) - _tmp124 * sqrt_info(0, 0);
    _res_D_x3(1, 2) = _tmp123 * sqrt_info(1, 1) - _tmp124 * sqrt_info(1, 0);
    _res_D_x3(0, 3) = -_tmp123 * sqrt_info(0, 0) - _tmp124 * sqrt_info(0, 1);
    _res_D_x3(1, 3) = -_tmp123 * sqrt_info(1, 0) - _tmp124 * sqrt_info(1, 1);
  }

  if (res_D_x_T_y != nullptr) {
    Eigen::Map<Eigen::Matrix<Scalar, 2, 2, Eigen::RowMajor>> _res_D_x_T_y{res_D_x_T_y};

    _res_D_x_T_y(0, 0) = -sqrt_info(0, 0);
    _res_D_x_T_y(1, 0) = -sqrt_info(1, 0);
    _res_D_x_T_y(0, 1) = -sqrt_info(0, 1);
    _res_D_x_T_y(1, 1) = -sqrt_info(1, 1);
  }

  return _res;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym_ceres
