// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     FACTOR.hpp.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Core>

#include <sym/pose2.h>

namespace sym_ceres {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: spline3_pose2_sensor_relative_between_factor
 *
 * Args:
 *     lambdas_x: Matrix31
 *     x0: Pose2
 *     x1: Pose2
 *     x2: Pose2
 *     x3: Pose2
 *     x_T_a: Pose2
 *     a_T_b: Pose2
 *     lambdas_y: Matrix31
 *     y0: Pose2
 *     y1: Pose2
 *     y2: Pose2
 *     y3: Pose2
 *     y_T_b: Pose2
 *     sqrt_info: Matrix33
 *     epsilon: Scalar
 *
 * Outputs:
 *     res: Matrix31
 *     res_D_x0: (3x4) jacobian (result_dim x storage_dim) of res (3) wrt arg x0 (4) (row-major)
 *     res_D_x1: (3x4) jacobian (result_dim x storage_dim) of res (3) wrt arg x1 (4) (row-major)
 *     res_D_x2: (3x4) jacobian (result_dim x storage_dim) of res (3) wrt arg x2 (4) (row-major)
 *     res_D_x3: (3x4) jacobian (result_dim x storage_dim) of res (3) wrt arg x3 (4) (row-major)
 *     res_D_x_T_a: (3x4) jacobian (result_dim x storage_dim) of res (3) wrt arg x_T_a (4)
 * (row-major) res_D_y0: (3x4) jacobian (result_dim x storage_dim) of res (3) wrt arg y0 (4)
 * (row-major) res_D_y1: (3x4) jacobian (result_dim x storage_dim) of res (3) wrt arg y1 (4)
 * (row-major) res_D_y2: (3x4) jacobian (result_dim x storage_dim) of res (3) wrt arg y2 (4)
 * (row-major) res_D_y3: (3x4) jacobian (result_dim x storage_dim) of res (3) wrt arg y3 (4)
 * (row-major) res_D_y_T_b: (3x4) jacobian (result_dim x storage_dim) of res (3) wrt arg y_T_b (4)
 * (row-major)
 */
template <typename Scalar>
Eigen::Matrix<Scalar, 3, 1> Spline3Pose2SensorRelativeBetweenFactorWithJacobians1234589101112(
    const Eigen::Matrix<Scalar, 3, 1>& lambdas_x, const sym::Pose2<Scalar>& x0,
    const sym::Pose2<Scalar>& x1, const sym::Pose2<Scalar>& x2, const sym::Pose2<Scalar>& x3,
    const sym::Pose2<Scalar>& x_T_a, const sym::Pose2<Scalar>& a_T_b,
    const Eigen::Matrix<Scalar, 3, 1>& lambdas_y, const sym::Pose2<Scalar>& y0,
    const sym::Pose2<Scalar>& y1, const sym::Pose2<Scalar>& y2, const sym::Pose2<Scalar>& y3,
    const sym::Pose2<Scalar>& y_T_b, const Eigen::Matrix<Scalar, 3, 3>& sqrt_info,
    const Scalar epsilon, Scalar* const res_D_x0 = nullptr, Scalar* const res_D_x1 = nullptr,
    Scalar* const res_D_x2 = nullptr, Scalar* const res_D_x3 = nullptr,
    Scalar* const res_D_x_T_a = nullptr, Scalar* const res_D_y0 = nullptr,
    Scalar* const res_D_y1 = nullptr, Scalar* const res_D_y2 = nullptr,
    Scalar* const res_D_y3 = nullptr, Scalar* const res_D_y_T_b = nullptr) {
  // Total ops: 1375

  // Input arrays
  const Eigen::Matrix<Scalar, 4, 1>& _x0 = x0.Data();
  const Eigen::Matrix<Scalar, 4, 1>& _x1 = x1.Data();
  const Eigen::Matrix<Scalar, 4, 1>& _x2 = x2.Data();
  const Eigen::Matrix<Scalar, 4, 1>& _x3 = x3.Data();
  const Eigen::Matrix<Scalar, 4, 1>& _x_T_a = x_T_a.Data();
  const Eigen::Matrix<Scalar, 4, 1>& _a_T_b = a_T_b.Data();
  const Eigen::Matrix<Scalar, 4, 1>& _y0 = y0.Data();
  const Eigen::Matrix<Scalar, 4, 1>& _y1 = y1.Data();
  const Eigen::Matrix<Scalar, 4, 1>& _y2 = y2.Data();
  const Eigen::Matrix<Scalar, 4, 1>& _y3 = y3.Data();
  const Eigen::Matrix<Scalar, 4, 1>& _y_T_b = y_T_b.Data();

  // Intermediate terms (367)
  const Scalar _tmp0 = _x2[1] * _x3[0];
  const Scalar _tmp1 = _x2[0] * _x3[1];
  const Scalar _tmp2 = -_tmp0 + _tmp1;
  const Scalar _tmp3 = _x2[0] * _x3[0];
  const Scalar _tmp4 = _x2[1] * _x3[1];
  const Scalar _tmp5 = _tmp3 + _tmp4;
  const Scalar _tmp6 = _tmp5 + epsilon * ((((_tmp5) > 0) - ((_tmp5) < 0)) + Scalar(0.5));
  const Scalar _tmp7 = lambdas_x(2, 0) * std::atan2(_tmp2, _tmp6);
  const Scalar _tmp8 = std::cos(_tmp7);
  const Scalar _tmp9 = _x1[0] * _x2[1];
  const Scalar _tmp10 = _x1[1] * _x2[0];
  const Scalar _tmp11 = -_tmp10 + _tmp9;
  const Scalar _tmp12 = _x1[0] * _x2[0];
  const Scalar _tmp13 = _x1[1] * _x2[1];
  const Scalar _tmp14 = _tmp12 + _tmp13;
  const Scalar _tmp15 = _tmp14 + epsilon * ((((_tmp14) > 0) - ((_tmp14) < 0)) + Scalar(0.5));
  const Scalar _tmp16 = lambdas_x(1, 0) * std::atan2(_tmp11, _tmp15);
  const Scalar _tmp17 = std::cos(_tmp16);
  const Scalar _tmp18 = _tmp17 * _tmp8;
  const Scalar _tmp19 = std::sin(_tmp7);
  const Scalar _tmp20 = std::sin(_tmp16);
  const Scalar _tmp21 = _tmp19 * _tmp20;
  const Scalar _tmp22 = _tmp18 - _tmp21;
  const Scalar _tmp23 = _x0[1] * _x1[0];
  const Scalar _tmp24 = _x0[0] * _x1[1];
  const Scalar _tmp25 = -_tmp23 + _tmp24;
  const Scalar _tmp26 = _x0[1] * _x1[1];
  const Scalar _tmp27 = _x0[0] * _x1[0];
  const Scalar _tmp28 = _tmp26 + _tmp27;
  const Scalar _tmp29 = _tmp28 + epsilon * ((((_tmp28) > 0) - ((_tmp28) < 0)) + Scalar(0.5));
  const Scalar _tmp30 = lambdas_x(0, 0) * std::atan2(_tmp25, _tmp29);
  const Scalar _tmp31 = std::cos(_tmp30);
  const Scalar _tmp32 = _tmp22 * _tmp31;
  const Scalar _tmp33 = _tmp20 * _tmp8;
  const Scalar _tmp34 = _tmp17 * _tmp19;
  const Scalar _tmp35 = _tmp33 + _tmp34;
  const Scalar _tmp36 = std::sin(_tmp30);
  const Scalar _tmp37 = _tmp35 * _tmp36;
  const Scalar _tmp38 = _tmp32 - _tmp37;
  const Scalar _tmp39 = _tmp38 * _x0[1];
  const Scalar _tmp40 = _tmp22 * _tmp36;
  const Scalar _tmp41 = _tmp31 * _tmp35;
  const Scalar _tmp42 = _tmp40 + _tmp41;
  const Scalar _tmp43 = _tmp42 * _x0[0];
  const Scalar _tmp44 = _tmp39 + _tmp43;
  const Scalar _tmp45 = _tmp38 * _x0[0] - _tmp42 * _x0[1];
  const Scalar _tmp46 = -_tmp44 * _x_T_a[1] + _tmp45 * _x_T_a[0];
  const Scalar _tmp47 = _tmp44 * _x_T_a[2] + _tmp45 * _x_T_a[3] + _x0[3] +
                        lambdas_x(0, 0) * (-_x0[3] + _x1[3]) +
                        lambdas_x(1, 0) * (-_x1[3] + _x2[3]) + lambdas_x(2, 0) * (-_x2[3] + _x3[3]);
  const Scalar _tmp48 = _tmp46 * _tmp47;
  const Scalar _tmp49 = _tmp44 * _x_T_a[0];
  const Scalar _tmp50 = _tmp45 * _x_T_a[1];
  const Scalar _tmp51 = _tmp49 + _tmp50;
  const Scalar _tmp52 = -_tmp44 * _x_T_a[3] + _tmp45 * _x_T_a[2] + _x0[2] +
                        lambdas_x(0, 0) * (-_x0[2] + _x1[2]) +
                        lambdas_x(1, 0) * (-_x1[2] + _x2[2]) + lambdas_x(2, 0) * (-_x2[2] + _x3[2]);
  const Scalar _tmp53 = _y1[0] * _y2[1];
  const Scalar _tmp54 = _y1[1] * _y2[0];
  const Scalar _tmp55 = _tmp53 - _tmp54;
  const Scalar _tmp56 = _y1[0] * _y2[0];
  const Scalar _tmp57 = _y1[1] * _y2[1];
  const Scalar _tmp58 = _tmp56 + _tmp57;
  const Scalar _tmp59 = _tmp58 + epsilon * ((((_tmp58) > 0) - ((_tmp58) < 0)) + Scalar(0.5));
  const Scalar _tmp60 = lambdas_y(1, 0) * std::atan2(_tmp55, _tmp59);
  const Scalar _tmp61 = std::sin(_tmp60);
  const Scalar _tmp62 = _y2[0] * _y3[1];
  const Scalar _tmp63 = _y2[1] * _y3[0];
  const Scalar _tmp64 = _tmp62 - _tmp63;
  const Scalar _tmp65 = _y2[1] * _y3[1];
  const Scalar _tmp66 = _y2[0] * _y3[0];
  const Scalar _tmp67 = _tmp65 + _tmp66;
  const Scalar _tmp68 = _tmp67 + epsilon * ((((_tmp67) > 0) - ((_tmp67) < 0)) + Scalar(0.5));
  const Scalar _tmp69 = lambdas_y(2, 0) * std::atan2(_tmp64, _tmp68);
  const Scalar _tmp70 = std::cos(_tmp69);
  const Scalar _tmp71 = _tmp61 * _tmp70;
  const Scalar _tmp72 = std::cos(_tmp60);
  const Scalar _tmp73 = std::sin(_tmp69);
  const Scalar _tmp74 = _tmp72 * _tmp73;
  const Scalar _tmp75 = _tmp71 + _tmp74;
  const Scalar _tmp76 = _y0[1] * _y1[0];
  const Scalar _tmp77 = _y0[0] * _y1[1];
  const Scalar _tmp78 = -_tmp76 + _tmp77;
  const Scalar _tmp79 = _y0[0] * _y1[0];
  const Scalar _tmp80 = _y0[1] * _y1[1];
  const Scalar _tmp81 = _tmp79 + _tmp80;
  const Scalar _tmp82 = _tmp81 + epsilon * ((((_tmp81) > 0) - ((_tmp81) < 0)) + Scalar(0.5));
  const Scalar _tmp83 = lambdas_y(0, 0) * std::atan2(_tmp78, _tmp82);
  const Scalar _tmp84 = std::sin(_tmp83);
  const Scalar _tmp85 = _tmp75 * _tmp84;
  const Scalar _tmp86 = _tmp61 * _tmp73;
  const Scalar _tmp87 = _tmp70 * _tmp72;
  const Scalar _tmp88 = -_tmp86 + _tmp87;
  const Scalar _tmp89 = std::cos(_tmp83);
  const Scalar _tmp90 = _tmp88 * _tmp89;
  const Scalar _tmp91 = -_tmp85 + _tmp90;
  const Scalar _tmp92 = _tmp91 * _y0[1];
  const Scalar _tmp93 = _tmp75 * _tmp89;
  const Scalar _tmp94 = _tmp84 * _tmp88;
  const Scalar _tmp95 = _tmp93 + _tmp94;
  const Scalar _tmp96 = _tmp95 * _y0[0];
  const Scalar _tmp97 = _tmp92 + _tmp96;
  const Scalar _tmp98 = _tmp91 * _y0[0] - _tmp95 * _y0[1];
  const Scalar _tmp99 = _tmp97 * _y_T_b[2] + _tmp98 * _y_T_b[3] + _y0[3] +
                        lambdas_y(0, 0) * (-_y0[3] + _y1[3]) +
                        lambdas_y(1, 0) * (-_y1[3] + _y2[3]) + lambdas_y(2, 0) * (-_y2[3] + _y3[3]);
  const Scalar _tmp100 = _tmp46 * _tmp99;
  const Scalar _tmp101 =
      -_tmp97 * _y_T_b[3] + _tmp98 * _y_T_b[2] + _y0[2] + lambdas_y(0, 0) * (-_y0[2] + _y1[2]) +
      lambdas_y(1, 0) * (-_y1[2] + _y2[2]) + lambdas_y(2, 0) * (-_y2[2] + _y3[2]);
  const Scalar _tmp102 = -_a_T_b[3] + _tmp100 - _tmp101 * _tmp51 - _tmp48 + _tmp51 * _tmp52;
  const Scalar _tmp103 = _tmp46 * _tmp52;
  const Scalar _tmp104 = _tmp101 * _tmp46;
  const Scalar _tmp105 = -_a_T_b[2] - _tmp103 + _tmp104 - _tmp47 * _tmp51 + _tmp51 * _tmp99;
  const Scalar _tmp106 = _tmp97 * _y_T_b[0];
  const Scalar _tmp107 = _tmp98 * _y_T_b[1];
  const Scalar _tmp108 = _tmp106 + _tmp107;
  const Scalar _tmp109 = -_tmp97 * _y_T_b[1] + _tmp98 * _y_T_b[0];
  const Scalar _tmp110 = _tmp109 * _tmp46;
  const Scalar _tmp111 = _tmp108 * _tmp51 + _tmp110;
  const Scalar _tmp112 = _tmp109 * _tmp51;
  const Scalar _tmp113 = _tmp108 * _tmp46;
  const Scalar _tmp114 = -_tmp112 + _tmp113;
  const Scalar _tmp115 = _a_T_b[0] * _tmp114 - _a_T_b[1] * _tmp111;
  const Scalar _tmp116 = _a_T_b[0] * _tmp111 + _a_T_b[1] * _tmp114;
  const Scalar _tmp117 = _tmp116 + epsilon * ((((_tmp116) > 0) - ((_tmp116) < 0)) + Scalar(0.5));
  const Scalar _tmp118 = std::atan2(_tmp115, _tmp117);
  const Scalar _tmp119 = std::pow(_tmp25, Scalar(2));
  const Scalar _tmp120 = std::pow(_tmp29, Scalar(2));
  const Scalar _tmp121 = Scalar(1.0) / (_tmp120);
  const Scalar _tmp122 = Scalar(1.0) / (_tmp29);
  const Scalar _tmp123 = _tmp120 * lambdas_x(0, 0) / (_tmp119 + _tmp120);
  const Scalar _tmp124 = _tmp123 * (-_tmp119 * _tmp121 + _tmp122 * (-_tmp26 - _tmp27));
  const Scalar _tmp125 = -_tmp124 * _tmp40 - _tmp124 * _tmp41;
  const Scalar _tmp126 = _tmp124 * _tmp32 - _tmp124 * _tmp37;
  const Scalar _tmp127 = _tmp125 * _x0[1] + _tmp126 * _x0[0] + _tmp45;
  const Scalar _tmp128 = -_tmp39 - _tmp43;
  const Scalar _tmp129 = _tmp125 * _x0[0] - _tmp126 * _x0[1] + _tmp128;
  const Scalar _tmp130 = _tmp127 * _x_T_a[0] + _tmp129 * _x_T_a[1];
  const Scalar _tmp131 = -_tmp127 * _x_T_a[1] + _tmp129 * _x_T_a[0];
  const Scalar _tmp132 = _tmp108 * _tmp131 - _tmp109 * _tmp130;
  const Scalar _tmp133 = _tmp108 * _tmp130 + _tmp109 * _tmp131;
  const Scalar _tmp134 = std::pow(_tmp117, Scalar(2));
  const Scalar _tmp135 = _tmp115 / _tmp134;
  const Scalar _tmp136 = Scalar(1.0) / (_tmp117);
  const Scalar _tmp137 = -_tmp135 * (_a_T_b[0] * _tmp133 + _a_T_b[1] * _tmp132) +
                         _tmp136 * (_a_T_b[0] * _tmp132 - _a_T_b[1] * _tmp133);
  const Scalar _tmp138 = _tmp134 / (std::pow(_tmp115, Scalar(2)) + _tmp134);
  const Scalar _tmp139 = _tmp138 * sqrt_info(0, 0);
  const Scalar _tmp140 = -_tmp127 * _x_T_a[3] + _tmp129 * _x_T_a[2];
  const Scalar _tmp141 = _tmp127 * _x_T_a[2] + _tmp129 * _x_T_a[3];
  const Scalar _tmp142 = _tmp101 * _tmp131 - _tmp130 * _tmp47 + _tmp130 * _tmp99 -
                         _tmp131 * _tmp52 - _tmp140 * _tmp46 - _tmp141 * _tmp51;
  const Scalar _tmp143 = -_tmp101 * _tmp130 + _tmp130 * _tmp52 - _tmp131 * _tmp47 +
                         _tmp131 * _tmp99 + _tmp140 * _tmp51 - _tmp141 * _tmp46;
  const Scalar _tmp144 = _tmp137 * _tmp139 + _tmp142 * sqrt_info(0, 1) + _tmp143 * sqrt_info(0, 2);
  const Scalar _tmp145 = _tmp138 * sqrt_info(1, 0);
  const Scalar _tmp146 = _tmp137 * _tmp145 + _tmp142 * sqrt_info(1, 1) + _tmp143 * sqrt_info(1, 2);
  const Scalar _tmp147 = _tmp138 * sqrt_info(2, 0);
  const Scalar _tmp148 = _tmp137 * _tmp147 + _tmp142 * sqrt_info(2, 1) + _tmp143 * sqrt_info(2, 2);
  const Scalar _tmp149 = 1 - lambdas_x(0, 0);
  const Scalar _tmp150 = _tmp149 * _tmp46;
  const Scalar _tmp151 = _tmp149 * _tmp51;
  const Scalar _tmp152 = _tmp51 * sqrt_info(1, 2);
  const Scalar _tmp153 = _tmp46 * sqrt_info(0, 2);
  const Scalar _tmp154 = _tmp51 * sqrt_info(0, 1);
  const Scalar _tmp155 = std::pow(_tmp11, Scalar(2));
  const Scalar _tmp156 = std::pow(_tmp15, Scalar(2));
  const Scalar _tmp157 = Scalar(1.0) / (_tmp156);
  const Scalar _tmp158 = Scalar(1.0) / (_tmp15);
  const Scalar _tmp159 = _tmp156 * lambdas_x(1, 0) / (_tmp155 + _tmp156);
  const Scalar _tmp160 = _tmp159 * (-_tmp155 * _tmp157 + _tmp158 * (-_tmp12 - _tmp13));
  const Scalar _tmp161 = -_tmp160 * _tmp33 - _tmp160 * _tmp34;
  const Scalar _tmp162 = _tmp123 * (-_tmp121 * _tmp25 * (_tmp23 - _tmp24) + _tmp122 * _tmp28);
  const Scalar _tmp163 = _tmp160 * _tmp18 - _tmp160 * _tmp21;
  const Scalar _tmp164 = _tmp161 * _tmp36 + _tmp162 * _tmp32 - _tmp162 * _tmp37 + _tmp163 * _tmp31;
  const Scalar _tmp165 = _tmp161 * _tmp31 - _tmp162 * _tmp40 - _tmp162 * _tmp41 - _tmp163 * _tmp36;
  const Scalar _tmp166 = _tmp164 * _x0[0] + _tmp165 * _x0[1];
  const Scalar _tmp167 = -_tmp164 * _x0[1] + _tmp165 * _x0[0];
  const Scalar _tmp168 = _tmp166 * _x_T_a[0] + _tmp167 * _x_T_a[1];
  const Scalar _tmp169 = -_tmp166 * _x_T_a[1] + _tmp167 * _x_T_a[0];
  const Scalar _tmp170 = _tmp166 * _x_T_a[2] + _tmp167 * _x_T_a[3];
  const Scalar _tmp171 = -_tmp166 * _x_T_a[3] + _tmp167 * _x_T_a[2];
  const Scalar _tmp172 = _tmp101 * _tmp169 - _tmp168 * _tmp47 + _tmp168 * _tmp99 -
                         _tmp169 * _tmp52 - _tmp170 * _tmp51 - _tmp171 * _tmp46;
  const Scalar _tmp173 = _tmp108 * _tmp169 - _tmp109 * _tmp168;
  const Scalar _tmp174 = _tmp108 * _tmp168 + _tmp109 * _tmp169;
  const Scalar _tmp175 = -_tmp135 * (_a_T_b[0] * _tmp174 + _a_T_b[1] * _tmp173) +
                         _tmp136 * (_a_T_b[0] * _tmp173 - _a_T_b[1] * _tmp174);
  const Scalar _tmp176 = -_tmp101 * _tmp168 + _tmp168 * _tmp52 - _tmp169 * _tmp47 +
                         _tmp169 * _tmp99 - _tmp170 * _tmp46 + _tmp171 * _tmp51;
  const Scalar _tmp177 = _tmp139 * _tmp175 + _tmp172 * sqrt_info(0, 1) + _tmp176 * sqrt_info(0, 2);
  const Scalar _tmp178 = _tmp145 * _tmp175 + _tmp172 * sqrt_info(1, 1) + _tmp176 * sqrt_info(1, 2);
  const Scalar _tmp179 = _tmp147 * _tmp175 + _tmp172 * sqrt_info(2, 1) + _tmp176 * sqrt_info(2, 2);
  const Scalar _tmp180 = lambdas_x(0, 0) - lambdas_x(1, 0);
  const Scalar _tmp181 = _tmp46 * sqrt_info(0, 1);
  const Scalar _tmp182 = _tmp51 * sqrt_info(0, 2);
  const Scalar _tmp183 = _tmp180 * sqrt_info(1, 1);
  const Scalar _tmp184 = _tmp46 * sqrt_info(2, 1);
  const Scalar _tmp185 = _tmp51 * sqrt_info(2, 2);
  const Scalar _tmp186 = _tmp46 * sqrt_info(1, 2);
  const Scalar _tmp187 = _tmp46 * sqrt_info(2, 2);
  const Scalar _tmp188 = _tmp51 * sqrt_info(2, 1);
  const Scalar _tmp189 = _tmp159 * (-_tmp11 * _tmp157 * (_tmp10 - _tmp9) + _tmp14 * _tmp158);
  const Scalar _tmp190 = std::pow(_tmp2, Scalar(2));
  const Scalar _tmp191 = std::pow(_tmp6, Scalar(2));
  const Scalar _tmp192 = Scalar(1.0) / (_tmp191);
  const Scalar _tmp193 = Scalar(1.0) / (_tmp6);
  const Scalar _tmp194 = _tmp191 * lambdas_x(2, 0) / (_tmp190 + _tmp191);
  const Scalar _tmp195 = _tmp194 * (-_tmp190 * _tmp192 + _tmp193 * (-_tmp3 - _tmp4));
  const Scalar _tmp196 = -_tmp189 * _tmp33 - _tmp189 * _tmp34 - _tmp195 * _tmp33 - _tmp195 * _tmp34;
  const Scalar _tmp197 = _tmp18 * _tmp189 + _tmp18 * _tmp195 - _tmp189 * _tmp21 - _tmp195 * _tmp21;
  const Scalar _tmp198 = _tmp196 * _tmp31 - _tmp197 * _tmp36;
  const Scalar _tmp199 = _tmp196 * _tmp36 + _tmp197 * _tmp31;
  const Scalar _tmp200 = _tmp198 * _x0[0] - _tmp199 * _x0[1];
  const Scalar _tmp201 = _tmp198 * _x0[1] + _tmp199 * _x0[0];
  const Scalar _tmp202 = _tmp200 * _x_T_a[0] - _tmp201 * _x_T_a[1];
  const Scalar _tmp203 = _tmp200 * _x_T_a[1] + _tmp201 * _x_T_a[0];
  const Scalar _tmp204 = _tmp200 * _x_T_a[3] + _tmp201 * _x_T_a[2];
  const Scalar _tmp205 = _tmp200 * _x_T_a[2] - _tmp201 * _x_T_a[3];
  const Scalar _tmp206 = -_tmp101 * _tmp203 - _tmp202 * _tmp47 + _tmp202 * _tmp99 +
                         _tmp203 * _tmp52 - _tmp204 * _tmp46 + _tmp205 * _tmp51;
  const Scalar _tmp207 = _tmp101 * _tmp202 - _tmp202 * _tmp52 - _tmp203 * _tmp47 +
                         _tmp203 * _tmp99 - _tmp204 * _tmp51 - _tmp205 * _tmp46;
  const Scalar _tmp208 = _tmp108 * _tmp203 + _tmp109 * _tmp202;
  const Scalar _tmp209 = _tmp108 * _tmp202 - _tmp109 * _tmp203;
  const Scalar _tmp210 = -_tmp135 * (_a_T_b[0] * _tmp208 + _a_T_b[1] * _tmp209) +
                         _tmp136 * (_a_T_b[0] * _tmp209 - _a_T_b[1] * _tmp208);
  const Scalar _tmp211 = _tmp138 * _tmp210;
  const Scalar _tmp212 =
      _tmp206 * sqrt_info(0, 2) + _tmp207 * sqrt_info(0, 1) + _tmp211 * sqrt_info(0, 0);
  const Scalar _tmp213 =
      _tmp206 * sqrt_info(1, 2) + _tmp207 * sqrt_info(1, 1) + _tmp211 * sqrt_info(1, 0);
  const Scalar _tmp214 = _tmp147 * _tmp210 + _tmp206 * sqrt_info(2, 2) + _tmp207 * sqrt_info(2, 1);
  const Scalar _tmp215 = lambdas_x(1, 0) - lambdas_x(2, 0);
  const Scalar _tmp216 = _tmp215 * _tmp46;
  const Scalar _tmp217 = _tmp51 * sqrt_info(1, 1);
  const Scalar _tmp218 = _tmp194 * (-_tmp192 * _tmp2 * (_tmp0 - _tmp1) + _tmp193 * _tmp5);
  const Scalar _tmp219 = _tmp18 * _tmp218 - _tmp21 * _tmp218;
  const Scalar _tmp220 = -_tmp218 * _tmp33 - _tmp218 * _tmp34;
  const Scalar _tmp221 = -_tmp219 * _tmp36 + _tmp220 * _tmp31;
  const Scalar _tmp222 = _tmp219 * _tmp31 + _tmp220 * _tmp36;
  const Scalar _tmp223 = _tmp221 * _x0[0] - _tmp222 * _x0[1];
  const Scalar _tmp224 = _tmp221 * _x0[1] + _tmp222 * _x0[0];
  const Scalar _tmp225 = _tmp223 * _x_T_a[1] + _tmp224 * _x_T_a[0];
  const Scalar _tmp226 = _tmp223 * _x_T_a[0] - _tmp224 * _x_T_a[1];
  const Scalar _tmp227 = _tmp223 * _x_T_a[3] + _tmp224 * _x_T_a[2];
  const Scalar _tmp228 = _tmp223 * _x_T_a[2] - _tmp224 * _x_T_a[3];
  const Scalar _tmp229 = _tmp101 * _tmp226 - _tmp225 * _tmp47 + _tmp225 * _tmp99 -
                         _tmp226 * _tmp52 - _tmp227 * _tmp51 - _tmp228 * _tmp46;
  const Scalar _tmp230 = -_tmp101 * _tmp225 + _tmp225 * _tmp52 - _tmp226 * _tmp47 +
                         _tmp226 * _tmp99 - _tmp227 * _tmp46 + _tmp228 * _tmp51;
  const Scalar _tmp231 = _tmp108 * _tmp226 - _tmp109 * _tmp225;
  const Scalar _tmp232 = _tmp108 * _tmp225 + _tmp109 * _tmp226;
  const Scalar _tmp233 = -_tmp135 * (_a_T_b[0] * _tmp232 + _a_T_b[1] * _tmp231) +
                         _tmp136 * (_a_T_b[0] * _tmp231 - _a_T_b[1] * _tmp232);
  const Scalar _tmp234 = _tmp139 * _tmp233 + _tmp229 * sqrt_info(0, 1) + _tmp230 * sqrt_info(0, 2);
  const Scalar _tmp235 = _tmp145 * _tmp233 + _tmp229 * sqrt_info(1, 1) + _tmp230 * sqrt_info(1, 2);
  const Scalar _tmp236 = _tmp147 * _tmp233 + _tmp229 * sqrt_info(2, 1) + _tmp230 * sqrt_info(2, 2);
  const Scalar _tmp237 = _tmp46 * lambdas_x(2, 0);
  const Scalar _tmp238 = _tmp51 * lambdas_x(2, 0);
  const Scalar _tmp239 = -_tmp49 - _tmp50;
  const Scalar _tmp240 = _tmp103 - _tmp104 - _tmp239 * _tmp47 + _tmp239 * _tmp99;
  const Scalar _tmp241 = _tmp109 * _tmp239 + _tmp113;
  const Scalar _tmp242 = _tmp108 * _tmp239 - _tmp110;
  const Scalar _tmp243 = -_tmp135 * (_a_T_b[0] * _tmp241 + _a_T_b[1] * _tmp242) +
                         _tmp136 * (_a_T_b[0] * _tmp242 - _a_T_b[1] * _tmp241);
  const Scalar _tmp244 = _tmp100 + _tmp101 * _tmp239 - _tmp239 * _tmp52 - _tmp48;
  const Scalar _tmp245 = _tmp139 * _tmp243 + _tmp240 * sqrt_info(0, 2) + _tmp244 * sqrt_info(0, 1);
  const Scalar _tmp246 = _tmp145 * _tmp243 + _tmp240 * sqrt_info(1, 2) + _tmp244 * sqrt_info(1, 1);
  const Scalar _tmp247 = _tmp147 * _tmp243 + _tmp240 * sqrt_info(2, 2) + _tmp244 * sqrt_info(2, 1);
  const Scalar _tmp248 = -_tmp45 * _tmp46;
  const Scalar _tmp249 = _tmp248 - _tmp44 * _tmp51;
  const Scalar _tmp250 = _tmp45 * _tmp51;
  const Scalar _tmp251 = _tmp250 - _tmp44 * _tmp46;
  const Scalar _tmp252 = _tmp128 * _tmp51 + _tmp248;
  const Scalar _tmp253 = -_tmp128 * _tmp46 - _tmp250;
  const Scalar _tmp254 = std::pow(_tmp78, Scalar(2));
  const Scalar _tmp255 = std::pow(_tmp82, Scalar(2));
  const Scalar _tmp256 = Scalar(1.0) / (_tmp255);
  const Scalar _tmp257 = Scalar(1.0) / (_tmp82);
  const Scalar _tmp258 = _tmp255 * lambdas_y(0, 0) / (_tmp254 + _tmp255);
  const Scalar _tmp259 = _tmp258 * (-_tmp254 * _tmp256 + _tmp257 * (-_tmp79 - _tmp80));
  const Scalar _tmp260 = -_tmp259 * _tmp93 - _tmp259 * _tmp94;
  const Scalar _tmp261 = -_tmp259 * _tmp85 + _tmp259 * _tmp90;
  const Scalar _tmp262 = -_tmp92 - _tmp96;
  const Scalar _tmp263 = _tmp260 * _y0[0] - _tmp261 * _y0[1] + _tmp262;
  const Scalar _tmp264 = _tmp260 * _y0[1] + _tmp261 * _y0[0] + _tmp98;
  const Scalar _tmp265 = _tmp263 * _y_T_b[0] - _tmp264 * _y_T_b[1];
  const Scalar _tmp266 = _tmp263 * _y_T_b[1] + _tmp264 * _y_T_b[0];
  const Scalar _tmp267 = -_tmp265 * _tmp51 + _tmp266 * _tmp46;
  const Scalar _tmp268 = _tmp265 * _tmp46 + _tmp266 * _tmp51;
  const Scalar _tmp269 = -_tmp135 * (_a_T_b[0] * _tmp268 + _a_T_b[1] * _tmp267) +
                         _tmp136 * (_a_T_b[0] * _tmp267 - _a_T_b[1] * _tmp268);
  const Scalar _tmp270 = _tmp263 * _y_T_b[2] - _tmp264 * _y_T_b[3];
  const Scalar _tmp271 = _tmp263 * _y_T_b[3] + _tmp264 * _y_T_b[2];
  const Scalar _tmp272 = -_tmp270 * _tmp51 + _tmp271 * _tmp46;
  const Scalar _tmp273 = _tmp270 * _tmp46 + _tmp271 * _tmp51;
  const Scalar _tmp274 = _tmp139 * _tmp269 + _tmp272 * sqrt_info(0, 2) + _tmp273 * sqrt_info(0, 1);
  const Scalar _tmp275 = _tmp145 * _tmp269 + _tmp272 * sqrt_info(1, 2) + _tmp273 * sqrt_info(1, 1);
  const Scalar _tmp276 = _tmp147 * _tmp269 + _tmp272 * sqrt_info(2, 2) + _tmp273 * sqrt_info(2, 1);
  const Scalar _tmp277 = 1 - lambdas_y(0, 0);
  const Scalar _tmp278 = _tmp277 * _tmp46;
  const Scalar _tmp279 = _tmp277 * _tmp51;
  const Scalar _tmp280 = Scalar(1.0) / (_tmp59);
  const Scalar _tmp281 = std::pow(_tmp55, Scalar(2));
  const Scalar _tmp282 = std::pow(_tmp59, Scalar(2));
  const Scalar _tmp283 = Scalar(1.0) / (_tmp282);
  const Scalar _tmp284 = _tmp282 * lambdas_y(1, 0) / (_tmp281 + _tmp282);
  const Scalar _tmp285 = _tmp284 * (_tmp280 * (-_tmp56 - _tmp57) - _tmp281 * _tmp283);
  const Scalar _tmp286 = -_tmp285 * _tmp71 - _tmp285 * _tmp74;
  const Scalar _tmp287 = -_tmp285 * _tmp86 + _tmp285 * _tmp87;
  const Scalar _tmp288 = _tmp258 * (-_tmp256 * _tmp78 * (_tmp76 - _tmp77) + _tmp257 * _tmp81);
  const Scalar _tmp289 = _tmp286 * _tmp84 + _tmp287 * _tmp89 - _tmp288 * _tmp85 + _tmp288 * _tmp90;
  const Scalar _tmp290 = _tmp286 * _tmp89 - _tmp287 * _tmp84 - _tmp288 * _tmp93 - _tmp288 * _tmp94;
  const Scalar _tmp291 = -_tmp289 * _y0[1] + _tmp290 * _y0[0];
  const Scalar _tmp292 = _tmp289 * _y0[0] + _tmp290 * _y0[1];
  const Scalar _tmp293 = _tmp291 * _y_T_b[1] + _tmp292 * _y_T_b[0];
  const Scalar _tmp294 = _tmp291 * _y_T_b[0] - _tmp292 * _y_T_b[1];
  const Scalar _tmp295 = _tmp293 * _tmp46 - _tmp294 * _tmp51;
  const Scalar _tmp296 = _tmp293 * _tmp51 + _tmp294 * _tmp46;
  const Scalar _tmp297 = -_tmp135 * (_a_T_b[0] * _tmp296 + _a_T_b[1] * _tmp295) +
                         _tmp136 * (_a_T_b[0] * _tmp295 - _a_T_b[1] * _tmp296);
  const Scalar _tmp298 = _tmp291 * _y_T_b[2] - _tmp292 * _y_T_b[3];
  const Scalar _tmp299 = _tmp291 * _y_T_b[3] + _tmp292 * _y_T_b[2];
  const Scalar _tmp300 = _tmp298 * _tmp46 + _tmp299 * _tmp51;
  const Scalar _tmp301 = -_tmp298 * _tmp51 + _tmp299 * _tmp46;
  const Scalar _tmp302 = _tmp139 * _tmp297 + _tmp300 * sqrt_info(0, 1) + _tmp301 * sqrt_info(0, 2);
  const Scalar _tmp303 = _tmp145 * _tmp297 + _tmp300 * sqrt_info(1, 1) + _tmp301 * sqrt_info(1, 2);
  const Scalar _tmp304 = _tmp147 * _tmp297 + _tmp300 * sqrt_info(2, 1) + _tmp301 * sqrt_info(2, 2);
  const Scalar _tmp305 = lambdas_y(0, 0) - lambdas_y(1, 0);
  const Scalar _tmp306 = _tmp305 * sqrt_info(1, 1);
  const Scalar _tmp307 = Scalar(1.0) / (_tmp68);
  const Scalar _tmp308 = std::pow(_tmp64, Scalar(2));
  const Scalar _tmp309 = std::pow(_tmp68, Scalar(2));
  const Scalar _tmp310 = Scalar(1.0) / (_tmp309);
  const Scalar _tmp311 = _tmp309 * lambdas_y(2, 0) / (_tmp308 + _tmp309);
  const Scalar _tmp312 = _tmp311 * (_tmp307 * (-_tmp65 - _tmp66) - _tmp308 * _tmp310);
  const Scalar _tmp313 = _tmp284 * (_tmp280 * _tmp58 - _tmp283 * _tmp55 * (-_tmp53 + _tmp54));
  const Scalar _tmp314 = -_tmp312 * _tmp86 + _tmp312 * _tmp87 - _tmp313 * _tmp86 + _tmp313 * _tmp87;
  const Scalar _tmp315 = -_tmp312 * _tmp71 - _tmp312 * _tmp74 - _tmp313 * _tmp71 - _tmp313 * _tmp74;
  const Scalar _tmp316 = _tmp314 * _tmp89 + _tmp315 * _tmp84;
  const Scalar _tmp317 = -_tmp314 * _tmp84 + _tmp315 * _tmp89;
  const Scalar _tmp318 = _tmp316 * _y0[0] + _tmp317 * _y0[1];
  const Scalar _tmp319 = -_tmp316 * _y0[1] + _tmp317 * _y0[0];
  const Scalar _tmp320 = -_tmp318 * _y_T_b[3] + _tmp319 * _y_T_b[2];
  const Scalar _tmp321 = _tmp318 * _y_T_b[2] + _tmp319 * _y_T_b[3];
  const Scalar _tmp322 = -_tmp320 * _tmp51 + _tmp321 * _tmp46;
  const Scalar _tmp323 = _tmp320 * _tmp46 + _tmp321 * _tmp51;
  const Scalar _tmp324 = _tmp318 * _y_T_b[0] + _tmp319 * _y_T_b[1];
  const Scalar _tmp325 = -_tmp318 * _y_T_b[1] + _tmp319 * _y_T_b[0];
  const Scalar _tmp326 = _tmp324 * _tmp51 + _tmp325 * _tmp46;
  const Scalar _tmp327 = _tmp324 * _tmp46 - _tmp325 * _tmp51;
  const Scalar _tmp328 = -_tmp135 * (_a_T_b[0] * _tmp326 + _a_T_b[1] * _tmp327) +
                         _tmp136 * (_a_T_b[0] * _tmp327 - _a_T_b[1] * _tmp326);
  const Scalar _tmp329 = _tmp139 * _tmp328 + _tmp322 * sqrt_info(0, 2) + _tmp323 * sqrt_info(0, 1);
  const Scalar _tmp330 = _tmp145 * _tmp328 + _tmp322 * sqrt_info(1, 2) + _tmp323 * sqrt_info(1, 1);
  const Scalar _tmp331 = _tmp147 * _tmp328 + _tmp322 * sqrt_info(2, 2) + _tmp323 * sqrt_info(2, 1);
  const Scalar _tmp332 = lambdas_y(1, 0) - lambdas_y(2, 0);
  const Scalar _tmp333 = _tmp332 * _tmp46;
  const Scalar _tmp334 = _tmp311 * (_tmp307 * _tmp67 - _tmp310 * _tmp64 * (-_tmp62 + _tmp63));
  const Scalar _tmp335 = -_tmp334 * _tmp71 - _tmp334 * _tmp74;
  const Scalar _tmp336 = -_tmp334 * _tmp86 + _tmp334 * _tmp87;
  const Scalar _tmp337 = _tmp335 * _tmp84 + _tmp336 * _tmp89;
  const Scalar _tmp338 = _tmp335 * _tmp89 - _tmp336 * _tmp84;
  const Scalar _tmp339 = -_tmp337 * _y0[1] + _tmp338 * _y0[0];
  const Scalar _tmp340 = _tmp337 * _y0[0] + _tmp338 * _y0[1];
  const Scalar _tmp341 = _tmp339 * _y_T_b[2] - _tmp340 * _y_T_b[3];
  const Scalar _tmp342 = _tmp339 * _y_T_b[3] + _tmp340 * _y_T_b[2];
  const Scalar _tmp343 = _tmp341 * _tmp46 + _tmp342 * _tmp51;
  const Scalar _tmp344 = -_tmp341 * _tmp51 + _tmp342 * _tmp46;
  const Scalar _tmp345 = _tmp339 * _y_T_b[0] - _tmp340 * _y_T_b[1];
  const Scalar _tmp346 = _tmp339 * _y_T_b[1] + _tmp340 * _y_T_b[0];
  const Scalar _tmp347 = _tmp345 * _tmp46 + _tmp346 * _tmp51;
  const Scalar _tmp348 = -_tmp345 * _tmp51 + _tmp346 * _tmp46;
  const Scalar _tmp349 = _tmp138 * (-_tmp135 * (_a_T_b[0] * _tmp347 + _a_T_b[1] * _tmp348) +
                                    _tmp136 * (_a_T_b[0] * _tmp348 - _a_T_b[1] * _tmp347));
  const Scalar _tmp350 =
      _tmp343 * sqrt_info(0, 1) + _tmp344 * sqrt_info(0, 2) + _tmp349 * sqrt_info(0, 0);
  const Scalar _tmp351 =
      _tmp343 * sqrt_info(1, 1) + _tmp344 * sqrt_info(1, 2) + _tmp349 * sqrt_info(1, 0);
  const Scalar _tmp352 =
      _tmp343 * sqrt_info(2, 1) + _tmp344 * sqrt_info(2, 2) + _tmp349 * sqrt_info(2, 0);
  const Scalar _tmp353 = _tmp46 * lambdas_y(2, 0);
  const Scalar _tmp354 = _tmp51 * lambdas_y(2, 0);
  const Scalar _tmp355 = -_tmp106 - _tmp107;
  const Scalar _tmp356 = _tmp110 - _tmp355 * _tmp51;
  const Scalar _tmp357 = _tmp112 + _tmp355 * _tmp46;
  const Scalar _tmp358 = -_tmp135 * (_a_T_b[0] * _tmp357 + _a_T_b[1] * _tmp356) +
                         _tmp136 * (_a_T_b[0] * _tmp356 - _a_T_b[1] * _tmp357);
  const Scalar _tmp359 = _tmp358 * _y_T_b[1];
  const Scalar _tmp360 = _tmp358 * _y_T_b[0];
  const Scalar _tmp361 = _tmp46 * _tmp98;
  const Scalar _tmp362 = _tmp361 + _tmp51 * _tmp97;
  const Scalar _tmp363 = _tmp51 * _tmp98;
  const Scalar _tmp364 = -_tmp363 + _tmp46 * _tmp97;
  const Scalar _tmp365 = -_tmp262 * _tmp51 + _tmp361;
  const Scalar _tmp366 = _tmp262 * _tmp46 + _tmp363;

  // Output terms (11)
  Eigen::Matrix<Scalar, 3, 1> _res;

  _res(0, 0) = _tmp102 * sqrt_info(0, 2) + _tmp105 * sqrt_info(0, 1) + _tmp118 * sqrt_info(0, 0);
  _res(1, 0) = _tmp102 * sqrt_info(1, 2) + _tmp105 * sqrt_info(1, 1) + _tmp118 * sqrt_info(1, 0);
  _res(2, 0) = _tmp102 * sqrt_info(2, 2) + _tmp105 * sqrt_info(2, 1) + _tmp118 * sqrt_info(2, 0);

  if (res_D_x0 != nullptr) {
    Eigen::Map<Eigen::Matrix<Scalar, 3, 4, Eigen::RowMajor>> _res_D_x0{res_D_x0};

    _res_D_x0(0, 0) = -_tmp144 * _x0[1];
    _res_D_x0(1, 0) = -_tmp146 * _x0[1];
    _res_D_x0(2, 0) = -_tmp148 * _x0[1];
    _res_D_x0(0, 1) = _tmp144 * _x0[0];
    _res_D_x0(1, 1) = _tmp146 * _x0[0];
    _res_D_x0(2, 1) = _tmp148 * _x0[0];
    _res_D_x0(0, 2) = -_tmp150 * sqrt_info(0, 1) + _tmp151 * sqrt_info(0, 2);
    _res_D_x0(1, 2) = _tmp149 * _tmp152 - _tmp150 * sqrt_info(1, 1);
    _res_D_x0(2, 2) = -_tmp150 * sqrt_info(2, 1) + _tmp151 * sqrt_info(2, 2);
    _res_D_x0(0, 3) = -_tmp149 * _tmp153 - _tmp149 * _tmp154;
    _res_D_x0(1, 3) = -_tmp150 * sqrt_info(1, 2) - _tmp151 * sqrt_info(1, 1);
    _res_D_x0(2, 3) = -_tmp150 * sqrt_info(2, 2) - _tmp151 * sqrt_info(2, 1);
  }

  if (res_D_x1 != nullptr) {
    Eigen::Map<Eigen::Matrix<Scalar, 3, 4, Eigen::RowMajor>> _res_D_x1{res_D_x1};

    _res_D_x1(0, 0) = -_tmp177 * _x1[1];
    _res_D_x1(1, 0) = -_tmp178 * _x1[1];
    _res_D_x1(2, 0) = -_tmp179 * _x1[1];
    _res_D_x1(0, 1) = _tmp177 * _x1[0];
    _res_D_x1(1, 1) = _tmp178 * _x1[0];
    _res_D_x1(2, 1) = _tmp179 * _x1[0];
    _res_D_x1(0, 2) = -_tmp180 * _tmp181 + _tmp180 * _tmp182;
    _res_D_x1(1, 2) = _tmp152 * _tmp180 - _tmp183 * _tmp46;
    _res_D_x1(2, 2) = -_tmp180 * _tmp184 + _tmp180 * _tmp185;
    _res_D_x1(0, 3) = -_tmp153 * _tmp180 - _tmp154 * _tmp180;
    _res_D_x1(1, 3) = -_tmp180 * _tmp186 - _tmp183 * _tmp51;
    _res_D_x1(2, 3) = -_tmp180 * _tmp187 - _tmp180 * _tmp188;
  }

  if (res_D_x2 != nullptr) {
    Eigen::Map<Eigen::Matrix<Scalar, 3, 4, Eigen::RowMajor>> _res_D_x2{res_D_x2};

    _res_D_x2(0, 0) = -_tmp212 * _x2[1];
    _res_D_x2(1, 0) = -_tmp213 * _x2[1];
    _res_D_x2(2, 0) = -_tmp214 * _x2[1];
    _res_D_x2(0, 1) = _tmp212 * _x2[0];
    _res_D_x2(1, 1) = _tmp213 * _x2[0];
    _res_D_x2(2, 1) = _tmp214 * _x2[0];
    _res_D_x2(0, 2) = _tmp182 * _tmp215 - _tmp216 * sqrt_info(0, 1);
    _res_D_x2(1, 2) = _tmp152 * _tmp215 - _tmp216 * sqrt_info(1, 1);
    _res_D_x2(2, 2) = _tmp185 * _tmp215 - _tmp216 * sqrt_info(2, 1);
    _res_D_x2(0, 3) = -_tmp154 * _tmp215 - _tmp216 * sqrt_info(0, 2);
    _res_D_x2(1, 3) = -_tmp215 * _tmp217 - _tmp216 * sqrt_info(1, 2);
    _res_D_x2(2, 3) = -_tmp188 * _tmp215 - _tmp216 * sqrt_info(2, 2);
  }

  if (res_D_x3 != nullptr) {
    Eigen::Map<Eigen::Matrix<Scalar, 3, 4, Eigen::RowMajor>> _res_D_x3{res_D_x3};

    _res_D_x3(0, 0) = -_tmp234 * _x3[1];
    _res_D_x3(1, 0) = -_tmp235 * _x3[1];
    _res_D_x3(2, 0) = -_tmp236 * _x3[1];
    _res_D_x3(0, 1) = _tmp234 * _x3[0];
    _res_D_x3(1, 1) = _tmp235 * _x3[0];
    _res_D_x3(2, 1) = _tmp236 * _x3[0];
    _res_D_x3(0, 2) = -_tmp237 * sqrt_info(0, 1) + _tmp238 * sqrt_info(0, 2);
    _res_D_x3(1, 2) = -_tmp237 * sqrt_info(1, 1) + _tmp238 * sqrt_info(1, 2);
    _res_D_x3(2, 2) = -_tmp237 * sqrt_info(2, 1) + _tmp238 * sqrt_info(2, 2);
    _res_D_x3(0, 3) = -_tmp153 * lambdas_x(2, 0) - _tmp154 * lambdas_x(2, 0);
    _res_D_x3(1, 3) = -_tmp237 * sqrt_info(1, 2) - _tmp238 * sqrt_info(1, 1);
    _res_D_x3(2, 3) = -_tmp237 * sqrt_info(2, 2) - _tmp238 * sqrt_info(2, 1);
  }

  if (res_D_x_T_a != nullptr) {
    Eigen::Map<Eigen::Matrix<Scalar, 3, 4, Eigen::RowMajor>> _res_D_x_T_a{res_D_x_T_a};

    _res_D_x_T_a(0, 0) = -_tmp245 * _x_T_a[1];
    _res_D_x_T_a(1, 0) = -_tmp246 * _x_T_a[1];
    _res_D_x_T_a(2, 0) = -_tmp247 * _x_T_a[1];
    _res_D_x_T_a(0, 1) = _tmp245 * _x_T_a[0];
    _res_D_x_T_a(1, 1) = _tmp246 * _x_T_a[0];
    _res_D_x_T_a(2, 1) = _tmp247 * _x_T_a[0];
    _res_D_x_T_a(0, 2) = _tmp249 * sqrt_info(0, 1) + _tmp251 * sqrt_info(0, 2);
    _res_D_x_T_a(1, 2) = _tmp249 * sqrt_info(1, 1) + _tmp251 * sqrt_info(1, 2);
    _res_D_x_T_a(2, 2) = _tmp249 * sqrt_info(2, 1) + _tmp251 * sqrt_info(2, 2);
    _res_D_x_T_a(0, 3) = _tmp252 * sqrt_info(0, 2) + _tmp253 * sqrt_info(0, 1);
    _res_D_x_T_a(1, 3) = _tmp252 * sqrt_info(1, 2) + _tmp253 * sqrt_info(1, 1);
    _res_D_x_T_a(2, 3) = _tmp252 * sqrt_info(2, 2) + _tmp253 * sqrt_info(2, 1);
  }

  if (res_D_y0 != nullptr) {
    Eigen::Map<Eigen::Matrix<Scalar, 3, 4, Eigen::RowMajor>> _res_D_y0{res_D_y0};

    _res_D_y0(0, 0) = -_tmp274 * _y0[1];
    _res_D_y0(1, 0) = -_tmp275 * _y0[1];
    _res_D_y0(2, 0) = -_tmp276 * _y0[1];
    _res_D_y0(0, 1) = _tmp274 * _y0[0];
    _res_D_y0(1, 1) = _tmp275 * _y0[0];
    _res_D_y0(2, 1) = _tmp276 * _y0[0];
    _res_D_y0(0, 2) = _tmp278 * sqrt_info(0, 1) - _tmp279 * sqrt_info(0, 2);
    _res_D_y0(1, 2) = -_tmp152 * _tmp277 + _tmp278 * sqrt_info(1, 1);
    _res_D_y0(2, 2) = _tmp278 * sqrt_info(2, 1) - _tmp279 * sqrt_info(2, 2);
    _res_D_y0(0, 3) = _tmp153 * _tmp277 + _tmp154 * _tmp277;
    _res_D_y0(1, 3) = _tmp278 * sqrt_info(1, 2) + _tmp279 * sqrt_info(1, 1);
    _res_D_y0(2, 3) = _tmp278 * sqrt_info(2, 2) + _tmp279 * sqrt_info(2, 1);
  }

  if (res_D_y1 != nullptr) {
    Eigen::Map<Eigen::Matrix<Scalar, 3, 4, Eigen::RowMajor>> _res_D_y1{res_D_y1};

    _res_D_y1(0, 0) = -_tmp302 * _y1[1];
    _res_D_y1(1, 0) = -_tmp303 * _y1[1];
    _res_D_y1(2, 0) = -_tmp304 * _y1[1];
    _res_D_y1(0, 1) = _tmp302 * _y1[0];
    _res_D_y1(1, 1) = _tmp303 * _y1[0];
    _res_D_y1(2, 1) = _tmp304 * _y1[0];
    _res_D_y1(0, 2) = _tmp181 * _tmp305 - _tmp182 * _tmp305;
    _res_D_y1(1, 2) = -_tmp152 * _tmp305 + _tmp306 * _tmp46;
    _res_D_y1(2, 2) = _tmp184 * _tmp305 - _tmp185 * _tmp305;
    _res_D_y1(0, 3) = _tmp153 * _tmp305 + _tmp154 * _tmp305;
    _res_D_y1(1, 3) = _tmp186 * _tmp305 + _tmp306 * _tmp51;
    _res_D_y1(2, 3) = _tmp187 * _tmp305 + _tmp188 * _tmp305;
  }

  if (res_D_y2 != nullptr) {
    Eigen::Map<Eigen::Matrix<Scalar, 3, 4, Eigen::RowMajor>> _res_D_y2{res_D_y2};

    _res_D_y2(0, 0) = -_tmp329 * _y2[1];
    _res_D_y2(1, 0) = -_tmp330 * _y2[1];
    _res_D_y2(2, 0) = -_tmp331 * _y2[1];
    _res_D_y2(0, 1) = _tmp329 * _y2[0];
    _res_D_y2(1, 1) = _tmp330 * _y2[0];
    _res_D_y2(2, 1) = _tmp331 * _y2[0];
    _res_D_y2(0, 2) = -_tmp182 * _tmp332 + _tmp333 * sqrt_info(0, 1);
    _res_D_y2(1, 2) = -_tmp152 * _tmp332 + _tmp333 * sqrt_info(1, 1);
    _res_D_y2(2, 2) = -_tmp185 * _tmp332 + _tmp333 * sqrt_info(2, 1);
    _res_D_y2(0, 3) = _tmp154 * _tmp332 + _tmp333 * sqrt_info(0, 2);
    _res_D_y2(1, 3) = _tmp217 * _tmp332 + _tmp333 * sqrt_info(1, 2);
    _res_D_y2(2, 3) = _tmp188 * _tmp332 + _tmp333 * sqrt_info(2, 2);
  }

  if (res_D_y3 != nullptr) {
    Eigen::Map<Eigen::Matrix<Scalar, 3, 4, Eigen::RowMajor>> _res_D_y3{res_D_y3};

    _res_D_y3(0, 0) = -_tmp350 * _y3[1];
    _res_D_y3(1, 0) = -_tmp351 * _y3[1];
    _res_D_y3(2, 0) = -_tmp352 * _y3[1];
    _res_D_y3(0, 1) = _tmp350 * _y3[0];
    _res_D_y3(1, 1) = _tmp351 * _y3[0];
    _res_D_y3(2, 1) = _tmp352 * _y3[0];
    _res_D_y3(0, 2) = _tmp353 * sqrt_info(0, 1) - _tmp354 * sqrt_info(0, 2);
    _res_D_y3(1, 2) = _tmp353 * sqrt_info(1, 1) - _tmp354 * sqrt_info(1, 2);
    _res_D_y3(2, 2) = _tmp353 * sqrt_info(2, 1) - _tmp354 * sqrt_info(2, 2);
    _res_D_y3(0, 3) = _tmp153 * lambdas_y(2, 0) + _tmp154 * lambdas_y(2, 0);
    _res_D_y3(1, 3) = _tmp353 * sqrt_info(1, 2) + _tmp354 * sqrt_info(1, 1);
    _res_D_y3(2, 3) = _tmp353 * sqrt_info(2, 2) + _tmp354 * sqrt_info(2, 1);
  }

  if (res_D_y_T_b != nullptr) {
    Eigen::Map<Eigen::Matrix<Scalar, 3, 4, Eigen::RowMajor>> _res_D_y_T_b{res_D_y_T_b};

    _res_D_y_T_b(0, 0) = -_tmp139 * _tmp359;
    _res_D_y_T_b(1, 0) = -_tmp145 * _tmp359;
    _res_D_y_T_b(2, 0) = -_tmp147 * _tmp359;
    _res_D_y_T_b(0, 1) = _tmp139 * _tmp360;
    _res_D_y_T_b(1, 1) = _tmp145 * _tmp360;
    _res_D_y_T_b(2, 1) = _tmp147 * _tmp360;
    _res_D_y_T_b(0, 2) = _tmp362 * sqrt_info(0, 1) + _tmp364 * sqrt_info(0, 2);
    _res_D_y_T_b(1, 2) = _tmp362 * sqrt_info(1, 1) + _tmp364 * sqrt_info(1, 2);
    _res_D_y_T_b(2, 2) = _tmp362 * sqrt_info(2, 1) + _tmp364 * sqrt_info(2, 2);
    _res_D_y_T_b(0, 3) = _tmp365 * sqrt_info(0, 2) + _tmp366 * sqrt_info(0, 1);
    _res_D_y_T_b(1, 3) = _tmp365 * sqrt_info(1, 2) + _tmp366 * sqrt_info(1, 1);
    _res_D_y_T_b(2, 3) = _tmp365 * sqrt_info(2, 2) + _tmp366 * sqrt_info(2, 1);
  }

  return _res;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym_ceres
