// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     FACTOR.hpp.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Core>

namespace sym_ceres {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: spline3_r3_acceleration_factor
 *
 * Args:
 *     dt: Scalar
 *     lambdas: Matrix33
 *     x0: Matrix31
 *     x1: Matrix31
 *     x2: Matrix31
 *     x3: Matrix31
 *     acceleration: Matrix31
 *     sqrt_info: Matrix33
 *     epsilon: Scalar
 *
 * Outputs:
 *     res: Matrix31
 */
template <typename Scalar>
Eigen::Matrix<Scalar, 3, 1> Spline3R3AccelerationGlobalFactor(
    const Scalar dt, const Eigen::Matrix<Scalar, 3, 3>& lambdas,
    const Eigen::Matrix<Scalar, 3, 1>& x0, const Eigen::Matrix<Scalar, 3, 1>& x1,
    const Eigen::Matrix<Scalar, 3, 1>& x2, const Eigen::Matrix<Scalar, 3, 1>& x3,
    const Eigen::Matrix<Scalar, 3, 1>& acceleration, const Eigen::Matrix<Scalar, 3, 3>& sqrt_info,
    const Scalar epsilon) {
  // Total ops: 46

  // Unused inputs
  (void)epsilon;

  // Input arrays

  // Intermediate terms (4)
  const Scalar _tmp0 = std::pow(dt, Scalar(-2));
  const Scalar _tmp1 =
      _tmp0 * (lambdas(0, 2) * (-x0(0, 0) + x1(0, 0)) + lambdas(1, 2) * (-x1(0, 0) + x2(0, 0)) +
               lambdas(2, 2) * (-x2(0, 0) + x3(0, 0))) -
      acceleration(0, 0);
  const Scalar _tmp2 =
      _tmp0 * (lambdas(0, 2) * (-x0(2, 0) + x1(2, 0)) + lambdas(1, 2) * (-x1(2, 0) + x2(2, 0)) +
               lambdas(2, 2) * (-x2(2, 0) + x3(2, 0))) -
      acceleration(2, 0);
  const Scalar _tmp3 =
      _tmp0 * (lambdas(0, 2) * (-x0(1, 0) + x1(1, 0)) + lambdas(1, 2) * (-x1(1, 0) + x2(1, 0)) +
               lambdas(2, 2) * (-x2(1, 0) + x3(1, 0))) -
      acceleration(1, 0);

  // Output terms (1)
  Eigen::Matrix<Scalar, 3, 1> _res;

  _res(0, 0) = _tmp1 * sqrt_info(0, 0) + _tmp2 * sqrt_info(0, 2) + _tmp3 * sqrt_info(0, 1);
  _res(1, 0) = _tmp1 * sqrt_info(1, 0) + _tmp2 * sqrt_info(1, 2) + _tmp3 * sqrt_info(1, 1);
  _res(2, 0) = _tmp1 * sqrt_info(2, 0) + _tmp2 * sqrt_info(2, 2) + _tmp3 * sqrt_info(2, 1);

  return _res;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym_ceres
